#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ros2/diagnostic_msgs/DiagnosticStatus.proto
// Protobuf C++ Version: 5.29.0

#ifndef ros2_2fdiagnostic_5fmsgs_2fDiagnosticStatus_2eproto_2epb_2eh
#define ros2_2fdiagnostic_5fmsgs_2fDiagnosticStatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "ros2/diagnostic_msgs/KeyValue.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ros2_2fdiagnostic_5fmsgs_2fDiagnosticStatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ros2_2fdiagnostic_5fmsgs_2fDiagnosticStatus_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ros2_2fdiagnostic_5fmsgs_2fDiagnosticStatus_2eproto;
namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace diagnostic_msgs {
class DiagnosticStatus;
struct DiagnosticStatusDefaultTypeInternal;
extern DiagnosticStatusDefaultTypeInternal _DiagnosticStatus_default_instance_;
}  // namespace diagnostic_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace diagnostic_msgs {
enum DiagnosticStatus_Level : int {
  DiagnosticStatus_Level_OK = 0,
  DiagnosticStatus_Level_WARN = 1,
  DiagnosticStatus_Level_ERROR = 2,
  DiagnosticStatus_Level_STALE = 3,
  DiagnosticStatus_Level_DiagnosticStatus_Level_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DiagnosticStatus_Level_DiagnosticStatus_Level_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DiagnosticStatus_Level_IsValid(int value);
extern const uint32_t DiagnosticStatus_Level_internal_data_[];
constexpr DiagnosticStatus_Level DiagnosticStatus_Level_Level_MIN = static_cast<DiagnosticStatus_Level>(0);
constexpr DiagnosticStatus_Level DiagnosticStatus_Level_Level_MAX = static_cast<DiagnosticStatus_Level>(3);
constexpr int DiagnosticStatus_Level_Level_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
DiagnosticStatus_Level_descriptor();
template <typename T>
const std::string& DiagnosticStatus_Level_Name(T value) {
  static_assert(std::is_same<T, DiagnosticStatus_Level>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Level_Name().");
  return DiagnosticStatus_Level_Name(static_cast<DiagnosticStatus_Level>(value));
}
template <>
inline const std::string& DiagnosticStatus_Level_Name(DiagnosticStatus_Level value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DiagnosticStatus_Level_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool DiagnosticStatus_Level_Parse(absl::string_view name, DiagnosticStatus_Level* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DiagnosticStatus_Level>(
      DiagnosticStatus_Level_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_ros2 DiagnosticStatus final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus) */ {
 public:
  inline DiagnosticStatus() : DiagnosticStatus(nullptr) {}
  ~DiagnosticStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiagnosticStatus* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiagnosticStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiagnosticStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline DiagnosticStatus(const DiagnosticStatus& from) : DiagnosticStatus(nullptr, from) {}
  inline DiagnosticStatus(DiagnosticStatus&& from) noexcept
      : DiagnosticStatus(nullptr, std::move(from)) {}
  inline DiagnosticStatus& operator=(const DiagnosticStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiagnosticStatus& operator=(DiagnosticStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiagnosticStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const DiagnosticStatus* internal_default_instance() {
    return reinterpret_cast<const DiagnosticStatus*>(
        &_DiagnosticStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DiagnosticStatus& a, DiagnosticStatus& b) { a.Swap(&b); }
  inline void Swap(DiagnosticStatus* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiagnosticStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiagnosticStatus* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DiagnosticStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DiagnosticStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DiagnosticStatus& from) { DiagnosticStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiagnosticStatus* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus"; }

 protected:
  explicit DiagnosticStatus(::google::protobuf::Arena* arena);
  DiagnosticStatus(::google::protobuf::Arena* arena, const DiagnosticStatus& from);
  DiagnosticStatus(::google::protobuf::Arena* arena, DiagnosticStatus&& from) noexcept
      : DiagnosticStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Level = DiagnosticStatus_Level;
  static constexpr Level OK = DiagnosticStatus_Level_OK;
  static constexpr Level WARN = DiagnosticStatus_Level_WARN;
  static constexpr Level ERROR = DiagnosticStatus_Level_ERROR;
  static constexpr Level STALE = DiagnosticStatus_Level_STALE;
  static inline bool Level_IsValid(int value) {
    return DiagnosticStatus_Level_IsValid(value);
  }
  static constexpr Level Level_MIN = DiagnosticStatus_Level_Level_MIN;
  static constexpr Level Level_MAX = DiagnosticStatus_Level_Level_MAX;
  static constexpr int Level_ARRAYSIZE = DiagnosticStatus_Level_Level_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Level_descriptor() {
    return DiagnosticStatus_Level_descriptor();
  }
  template <typename T>
  static inline const std::string& Level_Name(T value) {
    return DiagnosticStatus_Level_Name(value);
  }
  static inline bool Level_Parse(absl::string_view name, Level* value) {
    return DiagnosticStatus_Level_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kValuesFieldNumber = 5,
    kNameFieldNumber = 2,
    kMessageFieldNumber = 3,
    kHardwareIdFieldNumber = 4,
    kLevelFieldNumber = 1,
  };
  // repeated .humanoid_robot.PB.ros2.diagnostic_msgs.KeyValue values = 5;
  int values_size() const;
  private:
  int _internal_values_size() const;

  public:
  void clear_values() ;
  ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue* mutable_values(int index);
  ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>* mutable_values();

  private:
  const ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>& _internal_values() const;
  ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>* _internal_mutable_values();
  public:
  const ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue& values(int index) const;
  ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue* add_values();
  const ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>& values() const;
  // string name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // string message = 3;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // string hardware_id = 4;
  void clear_hardware_id() ;
  const std::string& hardware_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_hardware_id(Arg_&& arg, Args_... args);
  std::string* mutable_hardware_id();
  PROTOBUF_NODISCARD std::string* release_hardware_id();
  void set_allocated_hardware_id(std::string* value);

  private:
  const std::string& _internal_hardware_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hardware_id(
      const std::string& value);
  std::string* _internal_mutable_hardware_id();

  public:
  // .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.Level level = 1;
  void clear_level() ;
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level level() const;
  void set_level(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level value);

  private:
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level _internal_level() const;
  void _internal_set_level(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 1,
      86, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DiagnosticStatus& from_msg);
    ::google::protobuf::RepeatedPtrField< ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue > values_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::google::protobuf::internal::ArenaStringPtr hardware_id_;
    int level_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ros2_2fdiagnostic_5fmsgs_2fDiagnosticStatus_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DiagnosticStatus

// .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.Level level = 1;
inline void DiagnosticStatus::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0;
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level DiagnosticStatus::level() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.level)
  return _internal_level();
}
inline void DiagnosticStatus::set_level(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.level)
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level DiagnosticStatus::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level>(_impl_.level_);
}
inline void DiagnosticStatus::_internal_set_level(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// string name = 2;
inline void DiagnosticStatus::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& DiagnosticStatus::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DiagnosticStatus::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.name)
}
inline std::string* DiagnosticStatus::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.name)
  return _s;
}
inline const std::string& DiagnosticStatus::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void DiagnosticStatus::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* DiagnosticStatus::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* DiagnosticStatus::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.name)
  return _impl_.name_.Release();
}
inline void DiagnosticStatus::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.name)
}

// string message = 3;
inline void DiagnosticStatus::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& DiagnosticStatus::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DiagnosticStatus::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.message)
}
inline std::string* DiagnosticStatus::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.message)
  return _s;
}
inline const std::string& DiagnosticStatus::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void DiagnosticStatus::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* DiagnosticStatus::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* DiagnosticStatus::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.message)
  return _impl_.message_.Release();
}
inline void DiagnosticStatus::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.message)
}

// string hardware_id = 4;
inline void DiagnosticStatus::clear_hardware_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hardware_id_.ClearToEmpty();
}
inline const std::string& DiagnosticStatus::hardware_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.hardware_id)
  return _internal_hardware_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DiagnosticStatus::set_hardware_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hardware_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.hardware_id)
}
inline std::string* DiagnosticStatus::mutable_hardware_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_hardware_id();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.hardware_id)
  return _s;
}
inline const std::string& DiagnosticStatus::_internal_hardware_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hardware_id_.Get();
}
inline void DiagnosticStatus::_internal_set_hardware_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hardware_id_.Set(value, GetArena());
}
inline std::string* DiagnosticStatus::_internal_mutable_hardware_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hardware_id_.Mutable( GetArena());
}
inline std::string* DiagnosticStatus::release_hardware_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.hardware_id)
  return _impl_.hardware_id_.Release();
}
inline void DiagnosticStatus::set_allocated_hardware_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hardware_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hardware_id_.IsDefault()) {
    _impl_.hardware_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.hardware_id)
}

// repeated .humanoid_robot.PB.ros2.diagnostic_msgs.KeyValue values = 5;
inline int DiagnosticStatus::_internal_values_size() const {
  return _internal_values().size();
}
inline int DiagnosticStatus::values_size() const {
  return _internal_values_size();
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue* DiagnosticStatus::mutable_values(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.values)
  return _internal_mutable_values()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>* DiagnosticStatus::mutable_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.values)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_values();
}
inline const ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue& DiagnosticStatus::values(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.values)
  return _internal_values().Get(index);
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue* DiagnosticStatus::add_values() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue* _add = _internal_mutable_values()->Add();
  // @@protoc_insertion_point(field_add:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.values)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>& DiagnosticStatus::values() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticStatus.values)
  return _internal_values();
}
inline const ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>&
DiagnosticStatus::_internal_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.values_;
}
inline ::google::protobuf::RepeatedPtrField<::humanoid_robot::PB::ros2::diagnostic_msgs::KeyValue>*
DiagnosticStatus::_internal_mutable_values() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.values_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace diagnostic_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level>() {
  return ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticStatus_Level_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ros2_2fdiagnostic_5fmsgs_2fDiagnosticStatus_2eproto_2epb_2eh
