#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tangpa_ros2_interfaces/control/nlink_parser/LinktrackNode7.proto
// Protobuf C++ Version: 5.29.0

#ifndef tangpa_5fros2_5finterfaces_2fcontrol_2fnlink_5fparser_2fLinktrackNode7_2eproto_2epb_2eh
#define tangpa_5fros2_5finterfaces_2fcontrol_2fnlink_5fparser_2fLinktrackNode7_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_tangpa_5fros2_5finterfaces_2fcontrol_2fnlink_5fparser_2fLinktrackNode7_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_tangpa_5fros2_5finterfaces_2fcontrol_2fnlink_5fparser_2fLinktrackNode7_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_tangpa_5fros2_5finterfaces_2fcontrol_2fnlink_5fparser_2fLinktrackNode7_2eproto;
namespace humanoid_robot {
namespace PB {
namespace tangpa_ros2_interfaces {
namespace control {
namespace nlink_parser {
class LinktrackNode7;
struct LinktrackNode7DefaultTypeInternal;
extern LinktrackNode7DefaultTypeInternal _LinktrackNode7_default_instance_;
}  // namespace nlink_parser
}  // namespace control
}  // namespace tangpa_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace tangpa_ros2_interfaces {
namespace control {
namespace nlink_parser {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_tangpa_ros2_interfaces LinktrackNode7 final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7) */ {
 public:
  inline LinktrackNode7() : LinktrackNode7(nullptr) {}
  ~LinktrackNode7() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LinktrackNode7* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LinktrackNode7));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LinktrackNode7(
      ::google::protobuf::internal::ConstantInitialized);

  inline LinktrackNode7(const LinktrackNode7& from) : LinktrackNode7(nullptr, from) {}
  inline LinktrackNode7(LinktrackNode7&& from) noexcept
      : LinktrackNode7(nullptr, std::move(from)) {}
  inline LinktrackNode7& operator=(const LinktrackNode7& from) {
    CopyFrom(from);
    return *this;
  }
  inline LinktrackNode7& operator=(LinktrackNode7&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LinktrackNode7& default_instance() {
    return *internal_default_instance();
  }
  static inline const LinktrackNode7* internal_default_instance() {
    return reinterpret_cast<const LinktrackNode7*>(
        &_LinktrackNode7_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LinktrackNode7& a, LinktrackNode7& b) { a.Swap(&b); }
  inline void Swap(LinktrackNode7* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LinktrackNode7* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LinktrackNode7* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LinktrackNode7>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LinktrackNode7& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LinktrackNode7& from) { LinktrackNode7::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LinktrackNode7* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7"; }

 protected:
  explicit LinktrackNode7(::google::protobuf::Arena* arena);
  LinktrackNode7(::google::protobuf::Arena* arena, const LinktrackNode7& from);
  LinktrackNode7(::google::protobuf::Arena* arena, LinktrackNode7&& from) noexcept
      : LinktrackNode7(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRoleFieldNumber = 1,
    kIdFieldNumber = 2,
    kDisFieldNumber = 3,
    kAngle0FieldNumber = 4,
    kAngle1FieldNumber = 5,
    kFpRssiFieldNumber = 6,
    kRxRssiFieldNumber = 7,
  };
  // uint32 role = 1;
  void clear_role() ;
  ::uint32_t role() const;
  void set_role(::uint32_t value);

  private:
  ::uint32_t _internal_role() const;
  void _internal_set_role(::uint32_t value);

  public:
  // uint32 id = 2;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // float dis = 3;
  void clear_dis() ;
  float dis() const;
  void set_dis(float value);

  private:
  float _internal_dis() const;
  void _internal_set_dis(float value);

  public:
  // float angle0 = 4;
  void clear_angle0() ;
  float angle0() const;
  void set_angle0(float value);

  private:
  float _internal_angle0() const;
  void _internal_set_angle0(float value);

  public:
  // float angle1 = 5;
  void clear_angle1() ;
  float angle1() const;
  void set_angle1(float value);

  private:
  float _internal_angle1() const;
  void _internal_set_angle1(float value);

  public:
  // float fp_rssi = 6;
  void clear_fp_rssi() ;
  float fp_rssi() const;
  void set_fp_rssi(float value);

  private:
  float _internal_fp_rssi() const;
  void _internal_set_fp_rssi(float value);

  public:
  // float rx_rssi = 7;
  void clear_rx_rssi() ;
  float rx_rssi() const;
  void set_rx_rssi(float value);

  private:
  float _internal_rx_rssi() const;
  void _internal_set_rx_rssi(float value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LinktrackNode7& from_msg);
    ::uint32_t role_;
    ::uint32_t id_;
    float dis_;
    float angle0_;
    float angle1_;
    float fp_rssi_;
    float rx_rssi_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tangpa_5fros2_5finterfaces_2fcontrol_2fnlink_5fparser_2fLinktrackNode7_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LinktrackNode7

// uint32 role = 1;
inline void LinktrackNode7::clear_role() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.role_ = 0u;
}
inline ::uint32_t LinktrackNode7::role() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.role)
  return _internal_role();
}
inline void LinktrackNode7::set_role(::uint32_t value) {
  _internal_set_role(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.role)
}
inline ::uint32_t LinktrackNode7::_internal_role() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.role_;
}
inline void LinktrackNode7::_internal_set_role(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.role_ = value;
}

// uint32 id = 2;
inline void LinktrackNode7::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
}
inline ::uint32_t LinktrackNode7::id() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.id)
  return _internal_id();
}
inline void LinktrackNode7::set_id(::uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.id)
}
inline ::uint32_t LinktrackNode7::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void LinktrackNode7::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// float dis = 3;
inline void LinktrackNode7::clear_dis() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dis_ = 0;
}
inline float LinktrackNode7::dis() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.dis)
  return _internal_dis();
}
inline void LinktrackNode7::set_dis(float value) {
  _internal_set_dis(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.dis)
}
inline float LinktrackNode7::_internal_dis() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dis_;
}
inline void LinktrackNode7::_internal_set_dis(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dis_ = value;
}

// float angle0 = 4;
inline void LinktrackNode7::clear_angle0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angle0_ = 0;
}
inline float LinktrackNode7::angle0() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.angle0)
  return _internal_angle0();
}
inline void LinktrackNode7::set_angle0(float value) {
  _internal_set_angle0(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.angle0)
}
inline float LinktrackNode7::_internal_angle0() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.angle0_;
}
inline void LinktrackNode7::_internal_set_angle0(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angle0_ = value;
}

// float angle1 = 5;
inline void LinktrackNode7::clear_angle1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angle1_ = 0;
}
inline float LinktrackNode7::angle1() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.angle1)
  return _internal_angle1();
}
inline void LinktrackNode7::set_angle1(float value) {
  _internal_set_angle1(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.angle1)
}
inline float LinktrackNode7::_internal_angle1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.angle1_;
}
inline void LinktrackNode7::_internal_set_angle1(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angle1_ = value;
}

// float fp_rssi = 6;
inline void LinktrackNode7::clear_fp_rssi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fp_rssi_ = 0;
}
inline float LinktrackNode7::fp_rssi() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.fp_rssi)
  return _internal_fp_rssi();
}
inline void LinktrackNode7::set_fp_rssi(float value) {
  _internal_set_fp_rssi(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.fp_rssi)
}
inline float LinktrackNode7::_internal_fp_rssi() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fp_rssi_;
}
inline void LinktrackNode7::_internal_set_fp_rssi(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fp_rssi_ = value;
}

// float rx_rssi = 7;
inline void LinktrackNode7::clear_rx_rssi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_rssi_ = 0;
}
inline float LinktrackNode7::rx_rssi() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.rx_rssi)
  return _internal_rx_rssi();
}
inline void LinktrackNode7::set_rx_rssi(float value) {
  _internal_set_rx_rssi(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.tangpa_ros2_interfaces.control.nlink_parser.LinktrackNode7.rx_rssi)
}
inline float LinktrackNode7::_internal_rx_rssi() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_rssi_;
}
inline void LinktrackNode7::_internal_set_rx_rssi(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_rssi_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nlink_parser
}  // namespace control
}  // namespace tangpa_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // tangpa_5fros2_5finterfaces_2fcontrol_2fnlink_5fparser_2fLinktrackNode7_2eproto_2epb_2eh
