#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ros2/sensor_msgs/Joy.proto
// Protobuf C++ Version: 5.29.0

#ifndef ros2_2fsensor_5fmsgs_2fJoy_2eproto_2epb_2eh
#define ros2_2fsensor_5fmsgs_2fJoy_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ros2/std_msgs/Header.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ros2_2fsensor_5fmsgs_2fJoy_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ros2_2fsensor_5fmsgs_2fJoy_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ros2_2fsensor_5fmsgs_2fJoy_2eproto;
namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace sensor_msgs {
class Joy;
struct JoyDefaultTypeInternal;
extern JoyDefaultTypeInternal _Joy_default_instance_;
}  // namespace sensor_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace sensor_msgs {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_ros2 Joy final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.ros2.sensor_msgs.Joy) */ {
 public:
  inline Joy() : Joy(nullptr) {}
  ~Joy() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Joy* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Joy));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Joy(
      ::google::protobuf::internal::ConstantInitialized);

  inline Joy(const Joy& from) : Joy(nullptr, from) {}
  inline Joy(Joy&& from) noexcept
      : Joy(nullptr, std::move(from)) {}
  inline Joy& operator=(const Joy& from) {
    CopyFrom(from);
    return *this;
  }
  inline Joy& operator=(Joy&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Joy& default_instance() {
    return *internal_default_instance();
  }
  static inline const Joy* internal_default_instance() {
    return reinterpret_cast<const Joy*>(
        &_Joy_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Joy& a, Joy& b) { a.Swap(&b); }
  inline void Swap(Joy* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Joy* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Joy* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Joy>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Joy& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Joy& from) { Joy::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Joy* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.ros2.sensor_msgs.Joy"; }

 protected:
  explicit Joy(::google::protobuf::Arena* arena);
  Joy(::google::protobuf::Arena* arena, const Joy& from);
  Joy(::google::protobuf::Arena* arena, Joy&& from) noexcept
      : Joy(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAxesFieldNumber = 2,
    kButtonsFieldNumber = 3,
    kHeaderFieldNumber = 1,
  };
  // repeated float axes = 2;
  int axes_size() const;
  private:
  int _internal_axes_size() const;

  public:
  void clear_axes() ;
  float axes(int index) const;
  void set_axes(int index, float value);
  void add_axes(float value);
  const ::google::protobuf::RepeatedField<float>& axes() const;
  ::google::protobuf::RepeatedField<float>* mutable_axes();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_axes() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_axes();

  public:
  // repeated int32 buttons = 3;
  int buttons_size() const;
  private:
  int _internal_buttons_size() const;

  public:
  void clear_buttons() ;
  ::int32_t buttons(int index) const;
  void set_buttons(int index, ::int32_t value);
  void add_buttons(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& buttons() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_buttons();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_buttons() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_buttons();

  public:
  // .humanoid_robot.PB.ros2.std_msgs.Header header = 1;
  bool has_header() const;
  void clear_header() ;
  const ::humanoid_robot::PB::ros2::std_msgs::Header& header() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::std_msgs::Header* release_header();
  ::humanoid_robot::PB::ros2::std_msgs::Header* mutable_header();
  void set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value);
  void unsafe_arena_set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value);
  ::humanoid_robot::PB::ros2::std_msgs::Header* unsafe_arena_release_header();

  private:
  const ::humanoid_robot::PB::ros2::std_msgs::Header& _internal_header() const;
  ::humanoid_robot::PB::ros2::std_msgs::Header* _internal_mutable_header();

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.ros2.sensor_msgs.Joy)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Joy& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> axes_;
    ::google::protobuf::RepeatedField<::int32_t> buttons_;
    ::google::protobuf::internal::CachedSize _buttons_cached_byte_size_;
    ::humanoid_robot::PB::ros2::std_msgs::Header* header_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ros2_2fsensor_5fmsgs_2fJoy_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Joy

// .humanoid_robot.PB.ros2.std_msgs.Header header = 1;
inline bool Joy::has_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.header_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::std_msgs::Header& Joy::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::std_msgs::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::std_msgs::Header&>(::humanoid_robot::PB::ros2::std_msgs::_Header_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::std_msgs::Header& Joy::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Joy.header)
  return _internal_header();
}
inline void Joy::unsafe_arena_set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Joy.header)
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Joy::release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* released = _impl_.header_;
  _impl_.header_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Joy::unsafe_arena_release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.sensor_msgs.Joy.header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Joy::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::std_msgs::Header>(GetArena());
    _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(p);
  }
  return _impl_.header_;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Joy::mutable_header() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.sensor_msgs.Joy.header)
  return _msg;
}
inline void Joy::set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Joy.header)
}

// repeated float axes = 2;
inline int Joy::_internal_axes_size() const {
  return _internal_axes().size();
}
inline int Joy::axes_size() const {
  return _internal_axes_size();
}
inline void Joy::clear_axes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.axes_.Clear();
}
inline float Joy::axes(int index) const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Joy.axes)
  return _internal_axes().Get(index);
}
inline void Joy::set_axes(int index, float value) {
  _internal_mutable_axes()->Set(index, value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.sensor_msgs.Joy.axes)
}
inline void Joy::add_axes(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_axes()->Add(value);
  // @@protoc_insertion_point(field_add:humanoid_robot.PB.ros2.sensor_msgs.Joy.axes)
}
inline const ::google::protobuf::RepeatedField<float>& Joy::axes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:humanoid_robot.PB.ros2.sensor_msgs.Joy.axes)
  return _internal_axes();
}
inline ::google::protobuf::RepeatedField<float>* Joy::mutable_axes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:humanoid_robot.PB.ros2.sensor_msgs.Joy.axes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_axes();
}
inline const ::google::protobuf::RepeatedField<float>&
Joy::_internal_axes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.axes_;
}
inline ::google::protobuf::RepeatedField<float>* Joy::_internal_mutable_axes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.axes_;
}

// repeated int32 buttons = 3;
inline int Joy::_internal_buttons_size() const {
  return _internal_buttons().size();
}
inline int Joy::buttons_size() const {
  return _internal_buttons_size();
}
inline void Joy::clear_buttons() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buttons_.Clear();
}
inline ::int32_t Joy::buttons(int index) const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Joy.buttons)
  return _internal_buttons().Get(index);
}
inline void Joy::set_buttons(int index, ::int32_t value) {
  _internal_mutable_buttons()->Set(index, value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.sensor_msgs.Joy.buttons)
}
inline void Joy::add_buttons(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_buttons()->Add(value);
  // @@protoc_insertion_point(field_add:humanoid_robot.PB.ros2.sensor_msgs.Joy.buttons)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& Joy::buttons() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:humanoid_robot.PB.ros2.sensor_msgs.Joy.buttons)
  return _internal_buttons();
}
inline ::google::protobuf::RepeatedField<::int32_t>* Joy::mutable_buttons()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:humanoid_robot.PB.ros2.sensor_msgs.Joy.buttons)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_buttons();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
Joy::_internal_buttons() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.buttons_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* Joy::_internal_mutable_buttons() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.buttons_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sensor_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ros2_2fsensor_5fmsgs_2fJoy_2eproto_2epb_2eh
