#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/service.proto
// Protobuf C++ Version: 5.29.0

#ifndef common_2fservice_2eproto_2epb_2eh
#define common_2fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_common_2fservice_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace common {
enum CommandCode : int {
  UNKNOWN = 0,
  GET_CURRENT_POSE = 16777473,
  GET_GRID_MAP_2D = 16777474,
  NAVIGATION_TO = 16777729,
  CANCEL_NAVIGATION_TASK = 16777730,
  GET_REMAINING_PATH_DISTANCE = 16777731,
  START_CHARGING = 16777985,
  STOP_CHARGING = 16777986,
  GET_PERCEPTION_RESULT = 20001,
  GET_DETECTION_RESULT = 20002,
  GET_DIVISION_RESULT = 20003,
  CommandCode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  CommandCode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool CommandCode_IsValid(int value);
extern const uint32_t CommandCode_internal_data_[];
constexpr CommandCode CommandCode_MIN = static_cast<CommandCode>(0);
constexpr CommandCode CommandCode_MAX = static_cast<CommandCode>(16777986);
constexpr int CommandCode_ARRAYSIZE = 16777986 + 1;
const ::google::protobuf::EnumDescriptor*
CommandCode_descriptor();
template <typename T>
const std::string& CommandCode_Name(T value) {
  static_assert(std::is_same<T, CommandCode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to CommandCode_Name().");
  return ::google::protobuf::internal::NameOfEnum(CommandCode_descriptor(), value);
}
inline bool CommandCode_Parse(absl::string_view name, CommandCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CommandCode>(
      CommandCode_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace PB
}  // namespace humanoid_robot


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::humanoid_robot::PB::common::CommandCode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::humanoid_robot::PB::common::CommandCode>() {
  return ::humanoid_robot::PB::common::CommandCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // common_2fservice_2eproto_2epb_2eh
