// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api_service/common/status.proto
// Protobuf C++ Version: 5.29.0

#include "api_service/common/status.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace common {
}  // namespace common
}  // namespace api_service
}  // namespace PB
}  // namespace humanoid_robot
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_api_5fservice_2fcommon_2fstatus_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_api_5fservice_2fcommon_2fstatus_2eproto = nullptr;
const ::uint32_t TableStruct_api_5fservice_2fcommon_2fstatus_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_api_5fservice_2fcommon_2fstatus_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037api_service/common/status.proto\022$human"
    "oid_robot.PB.api_service.common*\325\003\n\014Comm"
    "onStatus\022\013\n\007SUCCESS\020\000\022\016\n\006FAILED\020\377\377\377\377\007\022\021\n"
    "\rERROR_TIMEOUT\020\001\022\026\n\022ERROR_PARSE_FAILED\020\002"
    "\022\032\n\026ERROR_SERIALIZE_FAILED\020\003\022\034\n\030ERROR_DE"
    "SERIALIZE_FAILED\020\004\022\032\n\024ERROR_CONNECT_FAIL"
    "ED\020\201\200@\022\031\n\023ERROR_NOT_CONNECTED\020\202\200@\022\027\n\021ERR"
    "OR_SEND_FAILED\020\203\200@\022\031\n\023ERROR_RECIVE_FAILE"
    "D\020\204\200@\022\034\n\025ERROR_UNKNOWN_SERVICE\020\201\200\200\001\022\033\n\024E"
    "RROR_CONVERT_FAILED\020\202\200\200\001\022\035\n\026ERROR_MODULE"
    "_NOT_FOUND\020\203\200\200\001\022\033\n\024ERROR_MODULE_STOPPED\020"
    "\204\200\200\001\022\037\n\030ERROR_MODULE_NOT_RUNNING\020\205\200\200\001\022\036\n"
    "\027ERROR_INVALID_PARAMETER\020\206\200\200\001\022 \n\031ERROR_S"
    "UBSYSTEM_NOT_READY\020\207\200\200\001b\006proto3"
};
static ::absl::once_flag descriptor_table_api_5fservice_2fcommon_2fstatus_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_5fservice_2fcommon_2fstatus_2eproto = {
    false,
    false,
    551,
    descriptor_table_protodef_api_5fservice_2fcommon_2fstatus_2eproto,
    "api_service/common/status.proto",
    &descriptor_table_api_5fservice_2fcommon_2fstatus_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_api_5fservice_2fcommon_2fstatus_2eproto::offsets,
    file_level_enum_descriptors_api_5fservice_2fcommon_2fstatus_2eproto,
    file_level_service_descriptors_api_5fservice_2fcommon_2fstatus_2eproto,
};
namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace common {
const ::google::protobuf::EnumDescriptor* CommonStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_api_5fservice_2fcommon_2fstatus_2eproto);
  return file_level_enum_descriptors_api_5fservice_2fcommon_2fstatus_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CommonStatus_internal_data_[] = {
    327680u, 786432u, 2097156u, 1048580u, 2097159u, 1048578u, 2097154u, 2097158u, 2147483647u, 1048577u, 1048579u, 2097153u, 2097155u, 2097157u, };
bool CommonStatus_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, CommonStatus_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace api_service
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_api_5fservice_2fcommon_2fstatus_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
