#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api_service/tangpa/control.proto
// Protobuf C++ Version: 5.29.0

#ifndef api_5fservice_2ftangpa_2fcontrol_2eproto_2epb_2eh
#define api_5fservice_2ftangpa_2fcontrol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ros2/diagnostic_msgs/DiagnosticArray.pb.h"
#include "ros2/geometry_msgs/Twist.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_api_5fservice_2ftangpa_2fcontrol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_api_5fservice_2ftangpa_2fcontrol_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_api_5fservice_2ftangpa_2fcontrol_2eproto;
namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace tangpa {
namespace control {
class JoyControllerResponse;
struct JoyControllerResponseDefaultTypeInternal;
extern JoyControllerResponseDefaultTypeInternal _JoyControllerResponse_default_instance_;
class MotorCalibrationRequest;
struct MotorCalibrationRequestDefaultTypeInternal;
extern MotorCalibrationRequestDefaultTypeInternal _MotorCalibrationRequest_default_instance_;
class MotorCalibrationResponse;
struct MotorCalibrationResponseDefaultTypeInternal;
extern MotorCalibrationResponseDefaultTypeInternal _MotorCalibrationResponse_default_instance_;
class UWBRequest;
struct UWBRequestDefaultTypeInternal;
extern UWBRequestDefaultTypeInternal _UWBRequest_default_instance_;
class UWBRequestConfig;
struct UWBRequestConfigDefaultTypeInternal;
extern UWBRequestConfigDefaultTypeInternal _UWBRequestConfig_default_instance_;
class UWBRequestHardware;
struct UWBRequestHardwareDefaultTypeInternal;
extern UWBRequestHardwareDefaultTypeInternal _UWBRequestHardware_default_instance_;
}  // namespace control
}  // namespace tangpa
}  // namespace api_service
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace tangpa {
namespace control {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_api_service_tangpa UWBRequestHardware final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware) */ {
 public:
  inline UWBRequestHardware() : UWBRequestHardware(nullptr) {}
  ~UWBRequestHardware() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UWBRequestHardware* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UWBRequestHardware));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UWBRequestHardware(
      ::google::protobuf::internal::ConstantInitialized);

  inline UWBRequestHardware(const UWBRequestHardware& from) : UWBRequestHardware(nullptr, from) {}
  inline UWBRequestHardware(UWBRequestHardware&& from) noexcept
      : UWBRequestHardware(nullptr, std::move(from)) {}
  inline UWBRequestHardware& operator=(const UWBRequestHardware& from) {
    CopyFrom(from);
    return *this;
  }
  inline UWBRequestHardware& operator=(UWBRequestHardware&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UWBRequestHardware& default_instance() {
    return *internal_default_instance();
  }
  static inline const UWBRequestHardware* internal_default_instance() {
    return reinterpret_cast<const UWBRequestHardware*>(
        &_UWBRequestHardware_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(UWBRequestHardware& a, UWBRequestHardware& b) { a.Swap(&b); }
  inline void Swap(UWBRequestHardware* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UWBRequestHardware* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UWBRequestHardware* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UWBRequestHardware>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UWBRequestHardware& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UWBRequestHardware& from) { UWBRequestHardware::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UWBRequestHardware* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware"; }

 protected:
  explicit UWBRequestHardware(::google::protobuf::Arena* arena);
  UWBRequestHardware(::google::protobuf::Arena* arena, const UWBRequestHardware& from);
  UWBRequestHardware(::google::protobuf::Arena* arena, UWBRequestHardware&& from) noexcept
      : UWBRequestHardware(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTargetDeviceFieldNumber = 1,
    kTargetRoleFieldNumber = 2,
    kBaudFieldNumber = 3,
  };
  // string target_device = 1;
  void clear_target_device() ;
  const std::string& target_device() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_target_device(Arg_&& arg, Args_... args);
  std::string* mutable_target_device();
  PROTOBUF_NODISCARD std::string* release_target_device();
  void set_allocated_target_device(std::string* value);

  private:
  const std::string& _internal_target_device() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_target_device(
      const std::string& value);
  std::string* _internal_mutable_target_device();

  public:
  // int32 target_role = 2;
  void clear_target_role() ;
  ::int32_t target_role() const;
  void set_target_role(::int32_t value);

  private:
  ::int32_t _internal_target_role() const;
  void _internal_set_target_role(::int32_t value);

  public:
  // int32 baud = 3;
  void clear_baud() ;
  ::int32_t baud() const;
  void set_baud(::int32_t value);

  private:
  ::int32_t _internal_baud() const;
  void _internal_set_baud(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      85, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UWBRequestHardware& from_msg);
    ::google::protobuf::internal::ArenaStringPtr target_device_;
    ::int32_t target_role_;
    ::int32_t baud_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5fservice_2ftangpa_2fcontrol_2eproto;
};
// -------------------------------------------------------------------

class chric_protobuf_api_service_tangpa UWBRequestConfig final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.api_service.tangpa.control.UWBRequestConfig) */ {
 public:
  inline UWBRequestConfig() : UWBRequestConfig(nullptr) {}
  ~UWBRequestConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UWBRequestConfig* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UWBRequestConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UWBRequestConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline UWBRequestConfig(const UWBRequestConfig& from) : UWBRequestConfig(nullptr, from) {}
  inline UWBRequestConfig(UWBRequestConfig&& from) noexcept
      : UWBRequestConfig(nullptr, std::move(from)) {}
  inline UWBRequestConfig& operator=(const UWBRequestConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline UWBRequestConfig& operator=(UWBRequestConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UWBRequestConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const UWBRequestConfig* internal_default_instance() {
    return reinterpret_cast<const UWBRequestConfig*>(
        &_UWBRequestConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UWBRequestConfig& a, UWBRequestConfig& b) { a.Swap(&b); }
  inline void Swap(UWBRequestConfig* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UWBRequestConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UWBRequestConfig* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UWBRequestConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UWBRequestConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UWBRequestConfig& from) { UWBRequestConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UWBRequestConfig* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.api_service.tangpa.control.UWBRequestConfig"; }

 protected:
  explicit UWBRequestConfig(::google::protobuf::Arena* arena);
  UWBRequestConfig(::google::protobuf::Arena* arena, const UWBRequestConfig& from);
  UWBRequestConfig(::google::protobuf::Arena* arena, UWBRequestConfig&& from) noexcept
      : UWBRequestConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTargetDistanceFieldNumber = 2,
    kTargetRoleFieldNumber = 1,
  };
  // double target_distance = 2;
  void clear_target_distance() ;
  double target_distance() const;
  void set_target_distance(double value);

  private:
  double _internal_target_distance() const;
  void _internal_set_target_distance(double value);

  public:
  // int32 target_role = 1;
  void clear_target_role() ;
  ::int32_t target_role() const;
  void set_target_role(::int32_t value);

  private:
  ::int32_t _internal_target_role() const;
  void _internal_set_target_role(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.api_service.tangpa.control.UWBRequestConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UWBRequestConfig& from_msg);
    double target_distance_;
    ::int32_t target_role_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5fservice_2ftangpa_2fcontrol_2eproto;
};
// -------------------------------------------------------------------

class chric_protobuf_api_service_tangpa UWBRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.api_service.tangpa.control.UWBRequest) */ {
 public:
  inline UWBRequest() : UWBRequest(nullptr) {}
  ~UWBRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UWBRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UWBRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UWBRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline UWBRequest(const UWBRequest& from) : UWBRequest(nullptr, from) {}
  inline UWBRequest(UWBRequest&& from) noexcept
      : UWBRequest(nullptr, std::move(from)) {}
  inline UWBRequest& operator=(const UWBRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UWBRequest& operator=(UWBRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UWBRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UWBRequest* internal_default_instance() {
    return reinterpret_cast<const UWBRequest*>(
        &_UWBRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(UWBRequest& a, UWBRequest& b) { a.Swap(&b); }
  inline void Swap(UWBRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UWBRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UWBRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UWBRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UWBRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UWBRequest& from) { UWBRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UWBRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.api_service.tangpa.control.UWBRequest"; }

 protected:
  explicit UWBRequest(::google::protobuf::Arena* arena);
  UWBRequest(::google::protobuf::Arena* arena, const UWBRequest& from);
  UWBRequest(::google::protobuf::Arena* arena, UWBRequest&& from) noexcept
      : UWBRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTargetDeviceFieldNumber = 1,
    kTargetRoleFieldNumber = 2,
    kBaudFieldNumber = 3,
  };
  // string target_device = 1;
  void clear_target_device() ;
  const std::string& target_device() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_target_device(Arg_&& arg, Args_... args);
  std::string* mutable_target_device();
  PROTOBUF_NODISCARD std::string* release_target_device();
  void set_allocated_target_device(std::string* value);

  private:
  const std::string& _internal_target_device() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_target_device(
      const std::string& value);
  std::string* _internal_mutable_target_device();

  public:
  // int32 target_role = 2;
  void clear_target_role() ;
  ::int32_t target_role() const;
  void set_target_role(::int32_t value);

  private:
  ::int32_t _internal_target_role() const;
  void _internal_set_target_role(::int32_t value);

  public:
  // int32 baud = 3;
  void clear_baud() ;
  ::int32_t baud() const;
  void set_baud(::int32_t value);

  private:
  ::int32_t _internal_baud() const;
  void _internal_set_baud(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.api_service.tangpa.control.UWBRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      77, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UWBRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr target_device_;
    ::int32_t target_role_;
    ::int32_t baud_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5fservice_2ftangpa_2fcontrol_2eproto;
};
// -------------------------------------------------------------------

class chric_protobuf_api_service_tangpa MotorCalibrationResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse) */ {
 public:
  inline MotorCalibrationResponse() : MotorCalibrationResponse(nullptr) {}
  ~MotorCalibrationResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MotorCalibrationResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MotorCalibrationResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MotorCalibrationResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline MotorCalibrationResponse(const MotorCalibrationResponse& from) : MotorCalibrationResponse(nullptr, from) {}
  inline MotorCalibrationResponse(MotorCalibrationResponse&& from) noexcept
      : MotorCalibrationResponse(nullptr, std::move(from)) {}
  inline MotorCalibrationResponse& operator=(const MotorCalibrationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorCalibrationResponse& operator=(MotorCalibrationResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MotorCalibrationResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MotorCalibrationResponse* internal_default_instance() {
    return reinterpret_cast<const MotorCalibrationResponse*>(
        &_MotorCalibrationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(MotorCalibrationResponse& a, MotorCalibrationResponse& b) { a.Swap(&b); }
  inline void Swap(MotorCalibrationResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorCalibrationResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MotorCalibrationResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MotorCalibrationResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MotorCalibrationResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MotorCalibrationResponse& from) { MotorCalibrationResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MotorCalibrationResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse"; }

 protected:
  explicit MotorCalibrationResponse(::google::protobuf::Arena* arena);
  MotorCalibrationResponse(::google::protobuf::Arena* arena, const MotorCalibrationResponse& from);
  MotorCalibrationResponse(::google::protobuf::Arena* arena, MotorCalibrationResponse&& from) noexcept
      : MotorCalibrationResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStateFieldNumber = 1,
    kMessageFieldNumber = 3,
    kMotorIdFieldNumber = 2,
  };
  // string state = 1;
  void clear_state() ;
  const std::string& state() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_state(Arg_&& arg, Args_... args);
  std::string* mutable_state();
  PROTOBUF_NODISCARD std::string* release_state();
  void set_allocated_state(std::string* value);

  private:
  const std::string& _internal_state() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_state(
      const std::string& value);
  std::string* _internal_mutable_state();

  public:
  // string message = 3;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // uint32 motor_id = 2;
  void clear_motor_id() ;
  ::uint32_t motor_id() const;
  void set_motor_id(::uint32_t value);

  private:
  ::uint32_t _internal_motor_id() const;
  void _internal_set_motor_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      90, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MotorCalibrationResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr state_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::uint32_t motor_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5fservice_2ftangpa_2fcontrol_2eproto;
};
// -------------------------------------------------------------------

class chric_protobuf_api_service_tangpa MotorCalibrationRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationRequest) */ {
 public:
  inline MotorCalibrationRequest() : MotorCalibrationRequest(nullptr) {}
  ~MotorCalibrationRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MotorCalibrationRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MotorCalibrationRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MotorCalibrationRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline MotorCalibrationRequest(const MotorCalibrationRequest& from) : MotorCalibrationRequest(nullptr, from) {}
  inline MotorCalibrationRequest(MotorCalibrationRequest&& from) noexcept
      : MotorCalibrationRequest(nullptr, std::move(from)) {}
  inline MotorCalibrationRequest& operator=(const MotorCalibrationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorCalibrationRequest& operator=(MotorCalibrationRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MotorCalibrationRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MotorCalibrationRequest* internal_default_instance() {
    return reinterpret_cast<const MotorCalibrationRequest*>(
        &_MotorCalibrationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(MotorCalibrationRequest& a, MotorCalibrationRequest& b) { a.Swap(&b); }
  inline void Swap(MotorCalibrationRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorCalibrationRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MotorCalibrationRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MotorCalibrationRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MotorCalibrationRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MotorCalibrationRequest& from) { MotorCalibrationRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MotorCalibrationRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationRequest"; }

 protected:
  explicit MotorCalibrationRequest(::google::protobuf::Arena* arena);
  MotorCalibrationRequest(::google::protobuf::Arena* arena, const MotorCalibrationRequest& from);
  MotorCalibrationRequest(::google::protobuf::Arena* arena, MotorCalibrationRequest&& from) noexcept
      : MotorCalibrationRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMotorIdFieldNumber = 1,
  };
  // uint32 motor_id = 1;
  void clear_motor_id() ;
  ::uint32_t motor_id() const;
  void set_motor_id(::uint32_t value);

  private:
  ::uint32_t _internal_motor_id() const;
  void _internal_set_motor_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MotorCalibrationRequest& from_msg);
    ::uint32_t motor_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5fservice_2ftangpa_2fcontrol_2eproto;
};
// -------------------------------------------------------------------

class chric_protobuf_api_service_tangpa JoyControllerResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse) */ {
 public:
  inline JoyControllerResponse() : JoyControllerResponse(nullptr) {}
  ~JoyControllerResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(JoyControllerResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(JoyControllerResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JoyControllerResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline JoyControllerResponse(const JoyControllerResponse& from) : JoyControllerResponse(nullptr, from) {}
  inline JoyControllerResponse(JoyControllerResponse&& from) noexcept
      : JoyControllerResponse(nullptr, std::move(from)) {}
  inline JoyControllerResponse& operator=(const JoyControllerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoyControllerResponse& operator=(JoyControllerResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JoyControllerResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const JoyControllerResponse* internal_default_instance() {
    return reinterpret_cast<const JoyControllerResponse*>(
        &_JoyControllerResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(JoyControllerResponse& a, JoyControllerResponse& b) { a.Swap(&b); }
  inline void Swap(JoyControllerResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JoyControllerResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JoyControllerResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<JoyControllerResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JoyControllerResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JoyControllerResponse& from) { JoyControllerResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(JoyControllerResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse"; }

 protected:
  explicit JoyControllerResponse(::google::protobuf::Arena* arena);
  JoyControllerResponse(::google::protobuf::Arena* arena, const JoyControllerResponse& from);
  JoyControllerResponse(::google::protobuf::Arena* arena, JoyControllerResponse&& from) noexcept
      : JoyControllerResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultsFieldNumber = 3,
  };
  // .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticArray results = 3;
  bool has_results() const;
  void clear_results() ;
  const ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray& results() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* release_results();
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* mutable_results();
  void set_allocated_results(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* value);
  void unsafe_arena_set_allocated_results(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* value);
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* unsafe_arena_release_results();

  private:
  const ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray& _internal_results() const;
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* _internal_mutable_results();

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const JoyControllerResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* results_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5fservice_2ftangpa_2fcontrol_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// JoyControllerResponse

// .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticArray results = 3;
inline bool JoyControllerResponse::has_results() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.results_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray& JoyControllerResponse::_internal_results() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* p = _impl_.results_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray&>(::humanoid_robot::PB::ros2::diagnostic_msgs::_DiagnosticArray_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray& JoyControllerResponse::results() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse.results)
  return _internal_results();
}
inline void JoyControllerResponse::unsafe_arena_set_allocated_results(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.results_);
  }
  _impl_.results_ = reinterpret_cast<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse.results)
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* JoyControllerResponse::release_results() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* released = _impl_.results_;
  _impl_.results_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* JoyControllerResponse::unsafe_arena_release_results() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse.results)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* temp = _impl_.results_;
  _impl_.results_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* JoyControllerResponse::_internal_mutable_results() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.results_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray>(GetArena());
    _impl_.results_ = reinterpret_cast<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray*>(p);
  }
  return _impl_.results_;
}
inline ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* JoyControllerResponse::mutable_results() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* _msg = _internal_mutable_results();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse.results)
  return _msg;
}
inline void JoyControllerResponse::set_allocated_results(::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.results_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.results_ = reinterpret_cast<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.api_service.tangpa.control.JoyControllerResponse.results)
}

// -------------------------------------------------------------------

// UWBRequestConfig

// int32 target_role = 1;
inline void UWBRequestConfig::clear_target_role() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_role_ = 0;
}
inline ::int32_t UWBRequestConfig::target_role() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequestConfig.target_role)
  return _internal_target_role();
}
inline void UWBRequestConfig::set_target_role(::int32_t value) {
  _internal_set_target_role(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequestConfig.target_role)
}
inline ::int32_t UWBRequestConfig::_internal_target_role() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_role_;
}
inline void UWBRequestConfig::_internal_set_target_role(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_role_ = value;
}

// double target_distance = 2;
inline void UWBRequestConfig::clear_target_distance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_distance_ = 0;
}
inline double UWBRequestConfig::target_distance() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequestConfig.target_distance)
  return _internal_target_distance();
}
inline void UWBRequestConfig::set_target_distance(double value) {
  _internal_set_target_distance(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequestConfig.target_distance)
}
inline double UWBRequestConfig::_internal_target_distance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_distance_;
}
inline void UWBRequestConfig::_internal_set_target_distance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_distance_ = value;
}

// -------------------------------------------------------------------

// UWBRequestHardware

// string target_device = 1;
inline void UWBRequestHardware::clear_target_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.ClearToEmpty();
}
inline const std::string& UWBRequestHardware::target_device() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.target_device)
  return _internal_target_device();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UWBRequestHardware::set_target_device(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.target_device)
}
inline std::string* UWBRequestHardware::mutable_target_device() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_target_device();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.target_device)
  return _s;
}
inline const std::string& UWBRequestHardware::_internal_target_device() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_device_.Get();
}
inline void UWBRequestHardware::_internal_set_target_device(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.Set(value, GetArena());
}
inline std::string* UWBRequestHardware::_internal_mutable_target_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.target_device_.Mutable( GetArena());
}
inline std::string* UWBRequestHardware::release_target_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.target_device)
  return _impl_.target_device_.Release();
}
inline void UWBRequestHardware::set_allocated_target_device(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.target_device_.IsDefault()) {
    _impl_.target_device_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.target_device)
}

// int32 target_role = 2;
inline void UWBRequestHardware::clear_target_role() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_role_ = 0;
}
inline ::int32_t UWBRequestHardware::target_role() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.target_role)
  return _internal_target_role();
}
inline void UWBRequestHardware::set_target_role(::int32_t value) {
  _internal_set_target_role(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.target_role)
}
inline ::int32_t UWBRequestHardware::_internal_target_role() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_role_;
}
inline void UWBRequestHardware::_internal_set_target_role(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_role_ = value;
}

// int32 baud = 3;
inline void UWBRequestHardware::clear_baud() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baud_ = 0;
}
inline ::int32_t UWBRequestHardware::baud() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.baud)
  return _internal_baud();
}
inline void UWBRequestHardware::set_baud(::int32_t value) {
  _internal_set_baud(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequestHardware.baud)
}
inline ::int32_t UWBRequestHardware::_internal_baud() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.baud_;
}
inline void UWBRequestHardware::_internal_set_baud(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baud_ = value;
}

// -------------------------------------------------------------------

// UWBRequest

// string target_device = 1;
inline void UWBRequest::clear_target_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.ClearToEmpty();
}
inline const std::string& UWBRequest::target_device() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.target_device)
  return _internal_target_device();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UWBRequest::set_target_device(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.target_device)
}
inline std::string* UWBRequest::mutable_target_device() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_target_device();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.target_device)
  return _s;
}
inline const std::string& UWBRequest::_internal_target_device() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_device_.Get();
}
inline void UWBRequest::_internal_set_target_device(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.Set(value, GetArena());
}
inline std::string* UWBRequest::_internal_mutable_target_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.target_device_.Mutable( GetArena());
}
inline std::string* UWBRequest::release_target_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.target_device)
  return _impl_.target_device_.Release();
}
inline void UWBRequest::set_allocated_target_device(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_device_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.target_device_.IsDefault()) {
    _impl_.target_device_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.target_device)
}

// int32 target_role = 2;
inline void UWBRequest::clear_target_role() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_role_ = 0;
}
inline ::int32_t UWBRequest::target_role() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.target_role)
  return _internal_target_role();
}
inline void UWBRequest::set_target_role(::int32_t value) {
  _internal_set_target_role(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.target_role)
}
inline ::int32_t UWBRequest::_internal_target_role() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_role_;
}
inline void UWBRequest::_internal_set_target_role(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_role_ = value;
}

// int32 baud = 3;
inline void UWBRequest::clear_baud() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baud_ = 0;
}
inline ::int32_t UWBRequest::baud() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.baud)
  return _internal_baud();
}
inline void UWBRequest::set_baud(::int32_t value) {
  _internal_set_baud(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.UWBRequest.baud)
}
inline ::int32_t UWBRequest::_internal_baud() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.baud_;
}
inline void UWBRequest::_internal_set_baud(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baud_ = value;
}

// -------------------------------------------------------------------

// MotorCalibrationRequest

// uint32 motor_id = 1;
inline void MotorCalibrationRequest::clear_motor_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motor_id_ = 0u;
}
inline ::uint32_t MotorCalibrationRequest::motor_id() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationRequest.motor_id)
  return _internal_motor_id();
}
inline void MotorCalibrationRequest::set_motor_id(::uint32_t value) {
  _internal_set_motor_id(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationRequest.motor_id)
}
inline ::uint32_t MotorCalibrationRequest::_internal_motor_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.motor_id_;
}
inline void MotorCalibrationRequest::_internal_set_motor_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motor_id_ = value;
}

// -------------------------------------------------------------------

// MotorCalibrationResponse

// string state = 1;
inline void MotorCalibrationResponse::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_.ClearToEmpty();
}
inline const std::string& MotorCalibrationResponse::state() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.state)
  return _internal_state();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MotorCalibrationResponse::set_state(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.state)
}
inline std::string* MotorCalibrationResponse::mutable_state() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.state)
  return _s;
}
inline const std::string& MotorCalibrationResponse::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.state_.Get();
}
inline void MotorCalibrationResponse::_internal_set_state(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_.Set(value, GetArena());
}
inline std::string* MotorCalibrationResponse::_internal_mutable_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.state_.Mutable( GetArena());
}
inline std::string* MotorCalibrationResponse::release_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.state)
  return _impl_.state_.Release();
}
inline void MotorCalibrationResponse::set_allocated_state(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.state_.IsDefault()) {
    _impl_.state_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.state)
}

// uint32 motor_id = 2;
inline void MotorCalibrationResponse::clear_motor_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motor_id_ = 0u;
}
inline ::uint32_t MotorCalibrationResponse::motor_id() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.motor_id)
  return _internal_motor_id();
}
inline void MotorCalibrationResponse::set_motor_id(::uint32_t value) {
  _internal_set_motor_id(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.motor_id)
}
inline ::uint32_t MotorCalibrationResponse::_internal_motor_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.motor_id_;
}
inline void MotorCalibrationResponse::_internal_set_motor_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motor_id_ = value;
}

// string message = 3;
inline void MotorCalibrationResponse::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& MotorCalibrationResponse::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MotorCalibrationResponse::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.message)
}
inline std::string* MotorCalibrationResponse::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.message)
  return _s;
}
inline const std::string& MotorCalibrationResponse::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void MotorCalibrationResponse::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* MotorCalibrationResponse::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* MotorCalibrationResponse::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.message)
  return _impl_.message_.Release();
}
inline void MotorCalibrationResponse::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.api_service.tangpa.control.MotorCalibrationResponse.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace control
}  // namespace tangpa
}  // namespace api_service
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // api_5fservice_2ftangpa_2fcontrol_2eproto_2epb_2eh
