#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: konka_ros2_interfaces/common/ccu2_interface/PWIN.proto
// Protobuf C++ Version: 5.29.0

#ifndef konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fPWIN_2eproto_2epb_2eh
#define konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fPWIN_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fPWIN_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fPWIN_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fPWIN_2eproto;
namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace common {
namespace ccu2_interface {
class PWIN;
struct PWINDefaultTypeInternal;
extern PWINDefaultTypeInternal _PWIN_default_instance_;
}  // namespace ccu2_interface
}  // namespace common
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace common {
namespace ccu2_interface {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_konka_ros2_interfaces PWIN final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.PWIN) */ {
 public:
  inline PWIN() : PWIN(nullptr) {}
  ~PWIN() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PWIN* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PWIN));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PWIN(
      ::google::protobuf::internal::ConstantInitialized);

  inline PWIN(const PWIN& from) : PWIN(nullptr, from) {}
  inline PWIN(PWIN&& from) noexcept
      : PWIN(nullptr, std::move(from)) {}
  inline PWIN& operator=(const PWIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline PWIN& operator=(PWIN&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PWIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const PWIN* internal_default_instance() {
    return reinterpret_cast<const PWIN*>(
        &_PWIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PWIN& a, PWIN& b) { a.Swap(&b); }
  inline void Swap(PWIN* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PWIN* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PWIN* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PWIN>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PWIN& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PWIN& from) { PWIN::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PWIN* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.PWIN"; }

 protected:
  explicit PWIN(::google::protobuf::Arena* arena);
  PWIN(::google::protobuf::Arena* arena, const PWIN& from);
  PWIN(::google::protobuf::Arena* arena, PWIN&& from) noexcept
      : PWIN(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVoltageFieldNumber = 1,
    kCurrentFieldNumber = 2,
  };
  // double voltage = 1;
  void clear_voltage() ;
  double voltage() const;
  void set_voltage(double value);

  private:
  double _internal_voltage() const;
  void _internal_set_voltage(double value);

  public:
  // double current = 2;
  void clear_current() ;
  double current() const;
  void set_current(double value);

  private:
  double _internal_current() const;
  void _internal_set_current(double value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.PWIN)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PWIN& from_msg);
    double voltage_;
    double current_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fPWIN_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PWIN

// double voltage = 1;
inline void PWIN::clear_voltage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.voltage_ = 0;
}
inline double PWIN::voltage() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.PWIN.voltage)
  return _internal_voltage();
}
inline void PWIN::set_voltage(double value) {
  _internal_set_voltage(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.PWIN.voltage)
}
inline double PWIN::_internal_voltage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.voltage_;
}
inline void PWIN::_internal_set_voltage(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.voltage_ = value;
}

// double current = 2;
inline void PWIN::clear_current() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = 0;
}
inline double PWIN::current() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.PWIN.current)
  return _internal_current();
}
inline void PWIN::set_current(double value) {
  _internal_set_current(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.PWIN.current)
}
inline double PWIN::_internal_current() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_;
}
inline void PWIN::_internal_set_current(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ccu2_interface
}  // namespace common
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fPWIN_2eproto_2epb_2eh
