#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: konka_ros2_interfaces/common/ccu2_interface/ServiceControlFan.proto
// Protobuf C++ Version: 5.29.0

#ifndef konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto_2epb_2eh
#define konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "konka_ros2_interfaces/common/ccu2_interface/ErrorCode.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto;
namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace common {
namespace ccu2_interface {
class ControlFanRequest;
struct ControlFanRequestDefaultTypeInternal;
extern ControlFanRequestDefaultTypeInternal _ControlFanRequest_default_instance_;
class ResponseControlFan;
struct ResponseControlFanDefaultTypeInternal;
extern ResponseControlFanDefaultTypeInternal _ResponseControlFan_default_instance_;
}  // namespace ccu2_interface
}  // namespace common
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace common {
namespace ccu2_interface {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_konka_ros2_interfaces ControlFanRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest) */ {
 public:
  inline ControlFanRequest() : ControlFanRequest(nullptr) {}
  ~ControlFanRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ControlFanRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ControlFanRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ControlFanRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ControlFanRequest(const ControlFanRequest& from) : ControlFanRequest(nullptr, from) {}
  inline ControlFanRequest(ControlFanRequest&& from) noexcept
      : ControlFanRequest(nullptr, std::move(from)) {}
  inline ControlFanRequest& operator=(const ControlFanRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlFanRequest& operator=(ControlFanRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlFanRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlFanRequest* internal_default_instance() {
    return reinterpret_cast<const ControlFanRequest*>(
        &_ControlFanRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ControlFanRequest& a, ControlFanRequest& b) { a.Swap(&b); }
  inline void Swap(ControlFanRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlFanRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlFanRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ControlFanRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlFanRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ControlFanRequest& from) { ControlFanRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ControlFanRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest"; }

 protected:
  explicit ControlFanRequest(::google::protobuf::Arena* arena);
  ControlFanRequest(::google::protobuf::Arena* arena, const ControlFanRequest& from);
  ControlFanRequest(::google::protobuf::Arena* arena, ControlFanRequest&& from) noexcept
      : ControlFanRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFan1DutyFieldNumber = 1,
    kFan2DutyFieldNumber = 2,
    kFan3DutyFieldNumber = 3,
    kFan4DutyFieldNumber = 4,
  };
  // optional uint32 fan1_duty = 1;
  bool has_fan1_duty() const;
  void clear_fan1_duty() ;
  ::uint32_t fan1_duty() const;
  void set_fan1_duty(::uint32_t value);

  private:
  ::uint32_t _internal_fan1_duty() const;
  void _internal_set_fan1_duty(::uint32_t value);

  public:
  // optional uint32 fan2_duty = 2;
  bool has_fan2_duty() const;
  void clear_fan2_duty() ;
  ::uint32_t fan2_duty() const;
  void set_fan2_duty(::uint32_t value);

  private:
  ::uint32_t _internal_fan2_duty() const;
  void _internal_set_fan2_duty(::uint32_t value);

  public:
  // optional uint32 fan3_duty = 3;
  bool has_fan3_duty() const;
  void clear_fan3_duty() ;
  ::uint32_t fan3_duty() const;
  void set_fan3_duty(::uint32_t value);

  private:
  ::uint32_t _internal_fan3_duty() const;
  void _internal_set_fan3_duty(::uint32_t value);

  public:
  // optional uint32 fan4_duty = 4;
  bool has_fan4_duty() const;
  void clear_fan4_duty() ;
  ::uint32_t fan4_duty() const;
  void set_fan4_duty(::uint32_t value);

  private:
  ::uint32_t _internal_fan4_duty() const;
  void _internal_set_fan4_duty(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ControlFanRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t fan1_duty_;
    ::uint32_t fan2_duty_;
    ::uint32_t fan3_duty_;
    ::uint32_t fan4_duty_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto;
};
// -------------------------------------------------------------------

class chric_protobuf_konka_ros2_interfaces ResponseControlFan final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan) */ {
 public:
  inline ResponseControlFan() : ResponseControlFan(nullptr) {}
  ~ResponseControlFan() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResponseControlFan* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResponseControlFan));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResponseControlFan(
      ::google::protobuf::internal::ConstantInitialized);

  inline ResponseControlFan(const ResponseControlFan& from) : ResponseControlFan(nullptr, from) {}
  inline ResponseControlFan(ResponseControlFan&& from) noexcept
      : ResponseControlFan(nullptr, std::move(from)) {}
  inline ResponseControlFan& operator=(const ResponseControlFan& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponseControlFan& operator=(ResponseControlFan&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResponseControlFan& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResponseControlFan* internal_default_instance() {
    return reinterpret_cast<const ResponseControlFan*>(
        &_ResponseControlFan_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ResponseControlFan& a, ResponseControlFan& b) { a.Swap(&b); }
  inline void Swap(ResponseControlFan* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResponseControlFan* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResponseControlFan* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResponseControlFan>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResponseControlFan& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResponseControlFan& from) { ResponseControlFan::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResponseControlFan* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan"; }

 protected:
  explicit ResponseControlFan(::google::protobuf::Arena* arena);
  ResponseControlFan(::google::protobuf::Arena* arena, const ResponseControlFan& from);
  ResponseControlFan(::google::protobuf::Arena* arena, ResponseControlFan&& from) noexcept
      : ResponseControlFan(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorCodeFieldNumber = 1,
  };
  // .humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ErrorCode error_code = 1;
  bool has_error_code() const;
  void clear_error_code() ;
  const ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode& error_code() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* release_error_code();
  ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* mutable_error_code();
  void set_allocated_error_code(::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* value);
  void unsafe_arena_set_allocated_error_code(::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* value);
  ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* unsafe_arena_release_error_code();

  private:
  const ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode& _internal_error_code() const;
  ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* _internal_mutable_error_code();

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ResponseControlFan& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* error_code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ControlFanRequest

// optional uint32 fan1_duty = 1;
inline bool ControlFanRequest::has_fan1_duty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ControlFanRequest::clear_fan1_duty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan1_duty_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t ControlFanRequest::fan1_duty() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan1_duty)
  return _internal_fan1_duty();
}
inline void ControlFanRequest::set_fan1_duty(::uint32_t value) {
  _internal_set_fan1_duty(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan1_duty)
}
inline ::uint32_t ControlFanRequest::_internal_fan1_duty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fan1_duty_;
}
inline void ControlFanRequest::_internal_set_fan1_duty(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan1_duty_ = value;
}

// optional uint32 fan2_duty = 2;
inline bool ControlFanRequest::has_fan2_duty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ControlFanRequest::clear_fan2_duty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan2_duty_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t ControlFanRequest::fan2_duty() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan2_duty)
  return _internal_fan2_duty();
}
inline void ControlFanRequest::set_fan2_duty(::uint32_t value) {
  _internal_set_fan2_duty(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan2_duty)
}
inline ::uint32_t ControlFanRequest::_internal_fan2_duty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fan2_duty_;
}
inline void ControlFanRequest::_internal_set_fan2_duty(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan2_duty_ = value;
}

// optional uint32 fan3_duty = 3;
inline bool ControlFanRequest::has_fan3_duty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ControlFanRequest::clear_fan3_duty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan3_duty_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t ControlFanRequest::fan3_duty() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan3_duty)
  return _internal_fan3_duty();
}
inline void ControlFanRequest::set_fan3_duty(::uint32_t value) {
  _internal_set_fan3_duty(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan3_duty)
}
inline ::uint32_t ControlFanRequest::_internal_fan3_duty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fan3_duty_;
}
inline void ControlFanRequest::_internal_set_fan3_duty(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan3_duty_ = value;
}

// optional uint32 fan4_duty = 4;
inline bool ControlFanRequest::has_fan4_duty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ControlFanRequest::clear_fan4_duty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan4_duty_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint32_t ControlFanRequest::fan4_duty() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan4_duty)
  return _internal_fan4_duty();
}
inline void ControlFanRequest::set_fan4_duty(::uint32_t value) {
  _internal_set_fan4_duty(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ControlFanRequest.fan4_duty)
}
inline ::uint32_t ControlFanRequest::_internal_fan4_duty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fan4_duty_;
}
inline void ControlFanRequest::_internal_set_fan4_duty(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fan4_duty_ = value;
}

// -------------------------------------------------------------------

// ResponseControlFan

// .humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ErrorCode error_code = 1;
inline bool ResponseControlFan::has_error_code() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.error_code_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode& ResponseControlFan::_internal_error_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* p = _impl_.error_code_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode&>(::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::_ErrorCode_default_instance_);
}
inline const ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode& ResponseControlFan::error_code() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan.error_code)
  return _internal_error_code();
}
inline void ResponseControlFan::unsafe_arena_set_allocated_error_code(::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.error_code_);
  }
  _impl_.error_code_ = reinterpret_cast<::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan.error_code)
}
inline ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* ResponseControlFan::release_error_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* released = _impl_.error_code_;
  _impl_.error_code_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* ResponseControlFan::unsafe_arena_release_error_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan.error_code)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* temp = _impl_.error_code_;
  _impl_.error_code_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* ResponseControlFan::_internal_mutable_error_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.error_code_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode>(GetArena());
    _impl_.error_code_ = reinterpret_cast<::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode*>(p);
  }
  return _impl_.error_code_;
}
inline ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* ResponseControlFan::mutable_error_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* _msg = _internal_mutable_error_code();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan.error_code)
  return _msg;
}
inline void ResponseControlFan::set_allocated_error_code(::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.error_code_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.error_code_ = reinterpret_cast<::humanoid_robot::PB::konka_ros2_interfaces::common::ccu2_interface::ErrorCode*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.ResponseControlFan.error_code)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ccu2_interface
}  // namespace common
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fServiceControlFan_2eproto_2epb_2eh
