#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: konka_ros2_interfaces/common/ccu2_interface/SwitchStatus.proto
// Protobuf C++ Version: 5.29.0

#ifndef konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fSwitchStatus_2eproto_2epb_2eh
#define konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fSwitchStatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ros2/std_msgs/Header.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fSwitchStatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fSwitchStatus_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fSwitchStatus_2eproto;
namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace common {
namespace ccu2_interface {
class SwitchStatus;
struct SwitchStatusDefaultTypeInternal;
extern SwitchStatusDefaultTypeInternal _SwitchStatus_default_instance_;
}  // namespace ccu2_interface
}  // namespace common
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace common {
namespace ccu2_interface {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_konka_ros2_interfaces SwitchStatus final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus) */ {
 public:
  inline SwitchStatus() : SwitchStatus(nullptr) {}
  ~SwitchStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SwitchStatus* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SwitchStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SwitchStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline SwitchStatus(const SwitchStatus& from) : SwitchStatus(nullptr, from) {}
  inline SwitchStatus(SwitchStatus&& from) noexcept
      : SwitchStatus(nullptr, std::move(from)) {}
  inline SwitchStatus& operator=(const SwitchStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline SwitchStatus& operator=(SwitchStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SwitchStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const SwitchStatus* internal_default_instance() {
    return reinterpret_cast<const SwitchStatus*>(
        &_SwitchStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SwitchStatus& a, SwitchStatus& b) { a.Swap(&b); }
  inline void Swap(SwitchStatus* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SwitchStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SwitchStatus* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SwitchStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SwitchStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SwitchStatus& from) { SwitchStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SwitchStatus* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus"; }

 protected:
  explicit SwitchStatus(::google::protobuf::Arena* arena);
  SwitchStatus(::google::protobuf::Arena* arena, const SwitchStatus& from);
  SwitchStatus(::google::protobuf::Arena* arena, SwitchStatus&& from) noexcept
      : SwitchStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHeaderFieldNumber = 1,
    kRelay1FieldNumber = 2,
    kRelay2FieldNumber = 3,
    kPhoto1FieldNumber = 4,
    kPhoto2FieldNumber = 5,
  };
  // .humanoid_robot.PB.ros2.std_msgs.Header header = 1;
  bool has_header() const;
  void clear_header() ;
  const ::humanoid_robot::PB::ros2::std_msgs::Header& header() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::std_msgs::Header* release_header();
  ::humanoid_robot::PB::ros2::std_msgs::Header* mutable_header();
  void set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value);
  void unsafe_arena_set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value);
  ::humanoid_robot::PB::ros2::std_msgs::Header* unsafe_arena_release_header();

  private:
  const ::humanoid_robot::PB::ros2::std_msgs::Header& _internal_header() const;
  ::humanoid_robot::PB::ros2::std_msgs::Header* _internal_mutable_header();

  public:
  // int32 relay1 = 2;
  void clear_relay1() ;
  ::int32_t relay1() const;
  void set_relay1(::int32_t value);

  private:
  ::int32_t _internal_relay1() const;
  void _internal_set_relay1(::int32_t value);

  public:
  // int32 relay2 = 3;
  void clear_relay2() ;
  ::int32_t relay2() const;
  void set_relay2(::int32_t value);

  private:
  ::int32_t _internal_relay2() const;
  void _internal_set_relay2(::int32_t value);

  public:
  // int32 photo1 = 4;
  void clear_photo1() ;
  ::int32_t photo1() const;
  void set_photo1(::int32_t value);

  private:
  ::int32_t _internal_photo1() const;
  void _internal_set_photo1(::int32_t value);

  public:
  // int32 photo2 = 5;
  void clear_photo2() ;
  ::int32_t photo2() const;
  void set_photo2(::int32_t value);

  private:
  ::int32_t _internal_photo2() const;
  void _internal_set_photo2(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SwitchStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::humanoid_robot::PB::ros2::std_msgs::Header* header_;
    ::int32_t relay1_;
    ::int32_t relay2_;
    ::int32_t photo1_;
    ::int32_t photo2_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fSwitchStatus_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SwitchStatus

// .humanoid_robot.PB.ros2.std_msgs.Header header = 1;
inline bool SwitchStatus::has_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.header_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::std_msgs::Header& SwitchStatus::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::std_msgs::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::std_msgs::Header&>(::humanoid_robot::PB::ros2::std_msgs::_Header_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::std_msgs::Header& SwitchStatus::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.header)
  return _internal_header();
}
inline void SwitchStatus::unsafe_arena_set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.header)
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* SwitchStatus::release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* released = _impl_.header_;
  _impl_.header_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* SwitchStatus::unsafe_arena_release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* SwitchStatus::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::std_msgs::Header>(GetArena());
    _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(p);
  }
  return _impl_.header_;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* SwitchStatus::mutable_header() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.header)
  return _msg;
}
inline void SwitchStatus::set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.header)
}

// int32 relay1 = 2;
inline void SwitchStatus::clear_relay1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.relay1_ = 0;
}
inline ::int32_t SwitchStatus::relay1() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.relay1)
  return _internal_relay1();
}
inline void SwitchStatus::set_relay1(::int32_t value) {
  _internal_set_relay1(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.relay1)
}
inline ::int32_t SwitchStatus::_internal_relay1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.relay1_;
}
inline void SwitchStatus::_internal_set_relay1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.relay1_ = value;
}

// int32 relay2 = 3;
inline void SwitchStatus::clear_relay2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.relay2_ = 0;
}
inline ::int32_t SwitchStatus::relay2() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.relay2)
  return _internal_relay2();
}
inline void SwitchStatus::set_relay2(::int32_t value) {
  _internal_set_relay2(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.relay2)
}
inline ::int32_t SwitchStatus::_internal_relay2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.relay2_;
}
inline void SwitchStatus::_internal_set_relay2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.relay2_ = value;
}

// int32 photo1 = 4;
inline void SwitchStatus::clear_photo1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.photo1_ = 0;
}
inline ::int32_t SwitchStatus::photo1() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.photo1)
  return _internal_photo1();
}
inline void SwitchStatus::set_photo1(::int32_t value) {
  _internal_set_photo1(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.photo1)
}
inline ::int32_t SwitchStatus::_internal_photo1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.photo1_;
}
inline void SwitchStatus::_internal_set_photo1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.photo1_ = value;
}

// int32 photo2 = 5;
inline void SwitchStatus::clear_photo2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.photo2_ = 0;
}
inline ::int32_t SwitchStatus::photo2() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.photo2)
  return _internal_photo2();
}
inline void SwitchStatus::set_photo2(::int32_t value) {
  _internal_set_photo2(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.common.ccu2_interface.SwitchStatus.photo2)
}
inline ::int32_t SwitchStatus::_internal_photo2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.photo2_;
}
inline void SwitchStatus::_internal_set_photo2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.photo2_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ccu2_interface
}  // namespace common
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // konka_5fros2_5finterfaces_2fcommon_2fccu2_5finterface_2fSwitchStatus_2eproto_2epb_2eh
