#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ros2/builtin_interfaces/Time.proto
// Protobuf C++ Version: 5.29.0

#ifndef ros2_2fbuiltin_5finterfaces_2fTime_2eproto_2epb_2eh
#define ros2_2fbuiltin_5finterfaces_2fTime_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ros2_2fbuiltin_5finterfaces_2fTime_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ros2_2fbuiltin_5finterfaces_2fTime_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ros2_2fbuiltin_5finterfaces_2fTime_2eproto;
namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace builtin_interfaces {
class Time;
struct TimeDefaultTypeInternal;
extern TimeDefaultTypeInternal _Time_default_instance_;
}  // namespace builtin_interfaces
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace builtin_interfaces {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_ros2 Time final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.ros2.builtin_interfaces.Time) */ {
 public:
  inline Time() : Time(nullptr) {}
  ~Time() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Time* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Time));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Time(
      ::google::protobuf::internal::ConstantInitialized);

  inline Time(const Time& from) : Time(nullptr, from) {}
  inline Time(Time&& from) noexcept
      : Time(nullptr, std::move(from)) {}
  inline Time& operator=(const Time& from) {
    CopyFrom(from);
    return *this;
  }
  inline Time& operator=(Time&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Time& default_instance() {
    return *internal_default_instance();
  }
  static inline const Time* internal_default_instance() {
    return reinterpret_cast<const Time*>(
        &_Time_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Time& a, Time& b) { a.Swap(&b); }
  inline void Swap(Time* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Time* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Time* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Time>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Time& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Time& from) { Time::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Time* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.ros2.builtin_interfaces.Time"; }

 protected:
  explicit Time(::google::protobuf::Arena* arena);
  Time(::google::protobuf::Arena* arena, const Time& from);
  Time(::google::protobuf::Arena* arena, Time&& from) noexcept
      : Time(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSecFieldNumber = 1,
    kNanosecFieldNumber = 2,
  };
  // int32 sec = 1;
  void clear_sec() ;
  ::int32_t sec() const;
  void set_sec(::int32_t value);

  private:
  ::int32_t _internal_sec() const;
  void _internal_set_sec(::int32_t value);

  public:
  // uint32 nanosec = 2;
  void clear_nanosec() ;
  ::uint32_t nanosec() const;
  void set_nanosec(::uint32_t value);

  private:
  ::uint32_t _internal_nanosec() const;
  void _internal_set_nanosec(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.ros2.builtin_interfaces.Time)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Time& from_msg);
    ::int32_t sec_;
    ::uint32_t nanosec_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ros2_2fbuiltin_5finterfaces_2fTime_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Time

// int32 sec = 1;
inline void Time::clear_sec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sec_ = 0;
}
inline ::int32_t Time::sec() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.builtin_interfaces.Time.sec)
  return _internal_sec();
}
inline void Time::set_sec(::int32_t value) {
  _internal_set_sec(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.builtin_interfaces.Time.sec)
}
inline ::int32_t Time::_internal_sec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sec_;
}
inline void Time::_internal_set_sec(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sec_ = value;
}

// uint32 nanosec = 2;
inline void Time::clear_nanosec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nanosec_ = 0u;
}
inline ::uint32_t Time::nanosec() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.builtin_interfaces.Time.nanosec)
  return _internal_nanosec();
}
inline void Time::set_nanosec(::uint32_t value) {
  _internal_set_nanosec(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.builtin_interfaces.Time.nanosec)
}
inline ::uint32_t Time::_internal_nanosec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nanosec_;
}
inline void Time::_internal_set_nanosec(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nanosec_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace builtin_interfaces
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ros2_2fbuiltin_5finterfaces_2fTime_2eproto_2epb_2eh
