#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ros2/sensor_msgs/Imu.proto
// Protobuf C++ Version: 5.29.0

#ifndef ros2_2fsensor_5fmsgs_2fImu_2eproto_2epb_2eh
#define ros2_2fsensor_5fmsgs_2fImu_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ros2/std_msgs/Header.pb.h"
#include "ros2/geometry_msgs/Quaternion.pb.h"
#include "ros2/geometry_msgs/Vector3.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ros2_2fsensor_5fmsgs_2fImu_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ros2_2fsensor_5fmsgs_2fImu_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ros2_2fsensor_5fmsgs_2fImu_2eproto;
namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace sensor_msgs {
class Imu;
struct ImuDefaultTypeInternal;
extern ImuDefaultTypeInternal _Imu_default_instance_;
}  // namespace sensor_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace sensor_msgs {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_ros2 Imu final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.ros2.sensor_msgs.Imu) */ {
 public:
  inline Imu() : Imu(nullptr) {}
  ~Imu() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Imu* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Imu));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Imu(
      ::google::protobuf::internal::ConstantInitialized);

  inline Imu(const Imu& from) : Imu(nullptr, from) {}
  inline Imu(Imu&& from) noexcept
      : Imu(nullptr, std::move(from)) {}
  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }
  inline Imu& operator=(Imu&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Imu& default_instance() {
    return *internal_default_instance();
  }
  static inline const Imu* internal_default_instance() {
    return reinterpret_cast<const Imu*>(
        &_Imu_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Imu& a, Imu& b) { a.Swap(&b); }
  inline void Swap(Imu* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Imu* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Imu* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Imu>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Imu& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Imu& from) { Imu::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Imu* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.ros2.sensor_msgs.Imu"; }

 protected:
  explicit Imu(::google::protobuf::Arena* arena);
  Imu(::google::protobuf::Arena* arena, const Imu& from);
  Imu(::google::protobuf::Arena* arena, Imu&& from) noexcept
      : Imu(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOrientationCovarianceFieldNumber = 3,
    kAngularVelocityCovarianceFieldNumber = 5,
    kLinearAccelerationCovarianceFieldNumber = 7,
    kHeaderFieldNumber = 1,
    kOrientationFieldNumber = 2,
    kAngularVelocityFieldNumber = 4,
    kLinearAccelerationFieldNumber = 6,
  };
  // repeated double orientation_covariance = 3;
  int orientation_covariance_size() const;
  private:
  int _internal_orientation_covariance_size() const;

  public:
  void clear_orientation_covariance() ;
  double orientation_covariance(int index) const;
  void set_orientation_covariance(int index, double value);
  void add_orientation_covariance(double value);
  const ::google::protobuf::RepeatedField<double>& orientation_covariance() const;
  ::google::protobuf::RepeatedField<double>* mutable_orientation_covariance();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_orientation_covariance() const;
  ::google::protobuf::RepeatedField<double>* _internal_mutable_orientation_covariance();

  public:
  // repeated double angular_velocity_covariance = 5;
  int angular_velocity_covariance_size() const;
  private:
  int _internal_angular_velocity_covariance_size() const;

  public:
  void clear_angular_velocity_covariance() ;
  double angular_velocity_covariance(int index) const;
  void set_angular_velocity_covariance(int index, double value);
  void add_angular_velocity_covariance(double value);
  const ::google::protobuf::RepeatedField<double>& angular_velocity_covariance() const;
  ::google::protobuf::RepeatedField<double>* mutable_angular_velocity_covariance();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_angular_velocity_covariance() const;
  ::google::protobuf::RepeatedField<double>* _internal_mutable_angular_velocity_covariance();

  public:
  // repeated double linear_acceleration_covariance = 7;
  int linear_acceleration_covariance_size() const;
  private:
  int _internal_linear_acceleration_covariance_size() const;

  public:
  void clear_linear_acceleration_covariance() ;
  double linear_acceleration_covariance(int index) const;
  void set_linear_acceleration_covariance(int index, double value);
  void add_linear_acceleration_covariance(double value);
  const ::google::protobuf::RepeatedField<double>& linear_acceleration_covariance() const;
  ::google::protobuf::RepeatedField<double>* mutable_linear_acceleration_covariance();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_linear_acceleration_covariance() const;
  ::google::protobuf::RepeatedField<double>* _internal_mutable_linear_acceleration_covariance();

  public:
  // .humanoid_robot.PB.ros2.std_msgs.Header header = 1;
  bool has_header() const;
  void clear_header() ;
  const ::humanoid_robot::PB::ros2::std_msgs::Header& header() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::std_msgs::Header* release_header();
  ::humanoid_robot::PB::ros2::std_msgs::Header* mutable_header();
  void set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value);
  void unsafe_arena_set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value);
  ::humanoid_robot::PB::ros2::std_msgs::Header* unsafe_arena_release_header();

  private:
  const ::humanoid_robot::PB::ros2::std_msgs::Header& _internal_header() const;
  ::humanoid_robot::PB::ros2::std_msgs::Header* _internal_mutable_header();

  public:
  // .humanoid_robot.PB.ros2.geometry_msgs.Quaternion orientation = 2;
  bool has_orientation() const;
  void clear_orientation() ;
  const ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion& orientation() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* release_orientation();
  ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* mutable_orientation();
  void set_allocated_orientation(::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* value);
  void unsafe_arena_set_allocated_orientation(::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* value);
  ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* unsafe_arena_release_orientation();

  private:
  const ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion& _internal_orientation() const;
  ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* _internal_mutable_orientation();

  public:
  // .humanoid_robot.PB.ros2.geometry_msgs.Vector3 angular_velocity = 4;
  bool has_angular_velocity() const;
  void clear_angular_velocity() ;
  const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& angular_velocity() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* release_angular_velocity();
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* mutable_angular_velocity();
  void set_allocated_angular_velocity(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value);
  void unsafe_arena_set_allocated_angular_velocity(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value);
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* unsafe_arena_release_angular_velocity();

  private:
  const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& _internal_angular_velocity() const;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* _internal_mutable_angular_velocity();

  public:
  // .humanoid_robot.PB.ros2.geometry_msgs.Vector3 linear_acceleration = 6;
  bool has_linear_acceleration() const;
  void clear_linear_acceleration() ;
  const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& linear_acceleration() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* release_linear_acceleration();
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* mutable_linear_acceleration();
  void set_allocated_linear_acceleration(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value);
  void unsafe_arena_set_allocated_linear_acceleration(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value);
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* unsafe_arena_release_linear_acceleration();

  private:
  const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& _internal_linear_acceleration() const;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* _internal_mutable_linear_acceleration();

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.ros2.sensor_msgs.Imu)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 4,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Imu& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> orientation_covariance_;
    ::google::protobuf::RepeatedField<double> angular_velocity_covariance_;
    ::google::protobuf::RepeatedField<double> linear_acceleration_covariance_;
    ::humanoid_robot::PB::ros2::std_msgs::Header* header_;
    ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* orientation_;
    ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* angular_velocity_;
    ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* linear_acceleration_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ros2_2fsensor_5fmsgs_2fImu_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Imu

// .humanoid_robot.PB.ros2.std_msgs.Header header = 1;
inline bool Imu::has_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.header_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::std_msgs::Header& Imu::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::std_msgs::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::std_msgs::Header&>(::humanoid_robot::PB::ros2::std_msgs::_Header_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::std_msgs::Header& Imu::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Imu.header)
  return _internal_header();
}
inline void Imu::unsafe_arena_set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.header)
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Imu::release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* released = _impl_.header_;
  _impl_.header_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Imu::unsafe_arena_release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.sensor_msgs.Imu.header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Imu::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::std_msgs::Header>(GetArena());
    _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(p);
  }
  return _impl_.header_;
}
inline ::humanoid_robot::PB::ros2::std_msgs::Header* Imu::mutable_header() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::humanoid_robot::PB::ros2::std_msgs::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.sensor_msgs.Imu.header)
  return _msg;
}
inline void Imu::set_allocated_header(::humanoid_robot::PB::ros2::std_msgs::Header* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.header_ = reinterpret_cast<::humanoid_robot::PB::ros2::std_msgs::Header*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.header)
}

// .humanoid_robot.PB.ros2.geometry_msgs.Quaternion orientation = 2;
inline bool Imu::has_orientation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.orientation_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion& Imu::_internal_orientation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* p = _impl_.orientation_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion&>(::humanoid_robot::PB::ros2::geometry_msgs::_Quaternion_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion& Imu::orientation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation)
  return _internal_orientation();
}
inline void Imu::unsafe_arena_set_allocated_orientation(::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.orientation_);
  }
  _impl_.orientation_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Quaternion*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation)
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* Imu::release_orientation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* released = _impl_.orientation_;
  _impl_.orientation_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* Imu::unsafe_arena_release_orientation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* temp = _impl_.orientation_;
  _impl_.orientation_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* Imu::_internal_mutable_orientation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.orientation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::geometry_msgs::Quaternion>(GetArena());
    _impl_.orientation_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Quaternion*>(p);
  }
  return _impl_.orientation_;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* Imu::mutable_orientation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* _msg = _internal_mutable_orientation();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation)
  return _msg;
}
inline void Imu::set_allocated_orientation(::humanoid_robot::PB::ros2::geometry_msgs::Quaternion* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.orientation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.orientation_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Quaternion*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation)
}

// repeated double orientation_covariance = 3;
inline int Imu::_internal_orientation_covariance_size() const {
  return _internal_orientation_covariance().size();
}
inline int Imu::orientation_covariance_size() const {
  return _internal_orientation_covariance_size();
}
inline void Imu::clear_orientation_covariance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.orientation_covariance_.Clear();
}
inline double Imu::orientation_covariance(int index) const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation_covariance)
  return _internal_orientation_covariance().Get(index);
}
inline void Imu::set_orientation_covariance(int index, double value) {
  _internal_mutable_orientation_covariance()->Set(index, value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation_covariance)
}
inline void Imu::add_orientation_covariance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_orientation_covariance()->Add(value);
  // @@protoc_insertion_point(field_add:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation_covariance)
}
inline const ::google::protobuf::RepeatedField<double>& Imu::orientation_covariance() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation_covariance)
  return _internal_orientation_covariance();
}
inline ::google::protobuf::RepeatedField<double>* Imu::mutable_orientation_covariance()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:humanoid_robot.PB.ros2.sensor_msgs.Imu.orientation_covariance)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_orientation_covariance();
}
inline const ::google::protobuf::RepeatedField<double>&
Imu::_internal_orientation_covariance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.orientation_covariance_;
}
inline ::google::protobuf::RepeatedField<double>* Imu::_internal_mutable_orientation_covariance() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.orientation_covariance_;
}

// .humanoid_robot.PB.ros2.geometry_msgs.Vector3 angular_velocity = 4;
inline bool Imu::has_angular_velocity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.angular_velocity_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& Imu::_internal_angular_velocity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* p = _impl_.angular_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3&>(::humanoid_robot::PB::ros2::geometry_msgs::_Vector3_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& Imu::angular_velocity() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity)
  return _internal_angular_velocity();
}
inline void Imu::unsafe_arena_set_allocated_angular_velocity(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angular_velocity_);
  }
  _impl_.angular_velocity_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Vector3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity)
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::release_angular_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* released = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::unsafe_arena_release_angular_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::_internal_mutable_angular_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.angular_velocity_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::geometry_msgs::Vector3>(GetArena());
    _impl_.angular_velocity_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Vector3*>(p);
  }
  return _impl_.angular_velocity_;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::mutable_angular_velocity() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* _msg = _internal_mutable_angular_velocity();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity)
  return _msg;
}
inline void Imu::set_allocated_angular_velocity(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angular_velocity_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.angular_velocity_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Vector3*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity)
}

// repeated double angular_velocity_covariance = 5;
inline int Imu::_internal_angular_velocity_covariance_size() const {
  return _internal_angular_velocity_covariance().size();
}
inline int Imu::angular_velocity_covariance_size() const {
  return _internal_angular_velocity_covariance_size();
}
inline void Imu::clear_angular_velocity_covariance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angular_velocity_covariance_.Clear();
}
inline double Imu::angular_velocity_covariance(int index) const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity_covariance)
  return _internal_angular_velocity_covariance().Get(index);
}
inline void Imu::set_angular_velocity_covariance(int index, double value) {
  _internal_mutable_angular_velocity_covariance()->Set(index, value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity_covariance)
}
inline void Imu::add_angular_velocity_covariance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_angular_velocity_covariance()->Add(value);
  // @@protoc_insertion_point(field_add:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity_covariance)
}
inline const ::google::protobuf::RepeatedField<double>& Imu::angular_velocity_covariance() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity_covariance)
  return _internal_angular_velocity_covariance();
}
inline ::google::protobuf::RepeatedField<double>* Imu::mutable_angular_velocity_covariance()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:humanoid_robot.PB.ros2.sensor_msgs.Imu.angular_velocity_covariance)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_angular_velocity_covariance();
}
inline const ::google::protobuf::RepeatedField<double>&
Imu::_internal_angular_velocity_covariance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.angular_velocity_covariance_;
}
inline ::google::protobuf::RepeatedField<double>* Imu::_internal_mutable_angular_velocity_covariance() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.angular_velocity_covariance_;
}

// .humanoid_robot.PB.ros2.geometry_msgs.Vector3 linear_acceleration = 6;
inline bool Imu::has_linear_acceleration() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.linear_acceleration_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& Imu::_internal_linear_acceleration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* p = _impl_.linear_acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3&>(::humanoid_robot::PB::ros2::geometry_msgs::_Vector3_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Vector3& Imu::linear_acceleration() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration)
  return _internal_linear_acceleration();
}
inline void Imu::unsafe_arena_set_allocated_linear_acceleration(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.linear_acceleration_);
  }
  _impl_.linear_acceleration_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Vector3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration)
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::release_linear_acceleration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* released = _impl_.linear_acceleration_;
  _impl_.linear_acceleration_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::unsafe_arena_release_linear_acceleration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* temp = _impl_.linear_acceleration_;
  _impl_.linear_acceleration_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::_internal_mutable_linear_acceleration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.linear_acceleration_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::geometry_msgs::Vector3>(GetArena());
    _impl_.linear_acceleration_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Vector3*>(p);
  }
  return _impl_.linear_acceleration_;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* Imu::mutable_linear_acceleration() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Vector3* _msg = _internal_mutable_linear_acceleration();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration)
  return _msg;
}
inline void Imu::set_allocated_linear_acceleration(::humanoid_robot::PB::ros2::geometry_msgs::Vector3* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.linear_acceleration_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.linear_acceleration_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Vector3*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration)
}

// repeated double linear_acceleration_covariance = 7;
inline int Imu::_internal_linear_acceleration_covariance_size() const {
  return _internal_linear_acceleration_covariance().size();
}
inline int Imu::linear_acceleration_covariance_size() const {
  return _internal_linear_acceleration_covariance_size();
}
inline void Imu::clear_linear_acceleration_covariance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.linear_acceleration_covariance_.Clear();
}
inline double Imu::linear_acceleration_covariance(int index) const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance().Get(index);
}
inline void Imu::set_linear_acceleration_covariance(int index, double value) {
  _internal_mutable_linear_acceleration_covariance()->Set(index, value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration_covariance)
}
inline void Imu::add_linear_acceleration_covariance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_linear_acceleration_covariance()->Add(value);
  // @@protoc_insertion_point(field_add:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration_covariance)
}
inline const ::google::protobuf::RepeatedField<double>& Imu::linear_acceleration_covariance() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance();
}
inline ::google::protobuf::RepeatedField<double>* Imu::mutable_linear_acceleration_covariance()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:humanoid_robot.PB.ros2.sensor_msgs.Imu.linear_acceleration_covariance)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_linear_acceleration_covariance();
}
inline const ::google::protobuf::RepeatedField<double>&
Imu::_internal_linear_acceleration_covariance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.linear_acceleration_covariance_;
}
inline ::google::protobuf::RepeatedField<double>* Imu::_internal_mutable_linear_acceleration_covariance() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.linear_acceleration_covariance_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sensor_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ros2_2fsensor_5fmsgs_2fImu_2eproto_2epb_2eh
