#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ros2/nav_msgs/MapMetaData.proto
// Protobuf C++ Version: 5.29.0

#ifndef ros2_2fnav_5fmsgs_2fMapMetaData_2eproto_2epb_2eh
#define ros2_2fnav_5fmsgs_2fMapMetaData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ros2/geometry_msgs/Pose.pb.h"
#include "ros2/builtin_interfaces/Time.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ros2_2fnav_5fmsgs_2fMapMetaData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ros2_2fnav_5fmsgs_2fMapMetaData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ros2_2fnav_5fmsgs_2fMapMetaData_2eproto;
namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace nav_msgs {
class MapMetaData;
struct MapMetaDataDefaultTypeInternal;
extern MapMetaDataDefaultTypeInternal _MapMetaData_default_instance_;
}  // namespace nav_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace ros2 {
namespace nav_msgs {

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_ros2 MapMetaData final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.ros2.nav_msgs.MapMetaData) */ {
 public:
  inline MapMetaData() : MapMetaData(nullptr) {}
  ~MapMetaData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MapMetaData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MapMetaData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MapMetaData(
      ::google::protobuf::internal::ConstantInitialized);

  inline MapMetaData(const MapMetaData& from) : MapMetaData(nullptr, from) {}
  inline MapMetaData(MapMetaData&& from) noexcept
      : MapMetaData(nullptr, std::move(from)) {}
  inline MapMetaData& operator=(const MapMetaData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapMetaData& operator=(MapMetaData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MapMetaData& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapMetaData* internal_default_instance() {
    return reinterpret_cast<const MapMetaData*>(
        &_MapMetaData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MapMetaData& a, MapMetaData& b) { a.Swap(&b); }
  inline void Swap(MapMetaData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapMetaData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MapMetaData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MapMetaData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MapMetaData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MapMetaData& from) { MapMetaData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MapMetaData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.ros2.nav_msgs.MapMetaData"; }

 protected:
  explicit MapMetaData(::google::protobuf::Arena* arena);
  MapMetaData(::google::protobuf::Arena* arena, const MapMetaData& from);
  MapMetaData(::google::protobuf::Arena* arena, MapMetaData&& from) noexcept
      : MapMetaData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMapLoadTimeFieldNumber = 1,
    kOriginFieldNumber = 5,
    kResolutionFieldNumber = 2,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
  };
  // .humanoid_robot.PB.ros2.builtin_interfaces.Time map_load_time = 1;
  bool has_map_load_time() const;
  void clear_map_load_time() ;
  const ::humanoid_robot::PB::ros2::builtin_interfaces::Time& map_load_time() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::builtin_interfaces::Time* release_map_load_time();
  ::humanoid_robot::PB::ros2::builtin_interfaces::Time* mutable_map_load_time();
  void set_allocated_map_load_time(::humanoid_robot::PB::ros2::builtin_interfaces::Time* value);
  void unsafe_arena_set_allocated_map_load_time(::humanoid_robot::PB::ros2::builtin_interfaces::Time* value);
  ::humanoid_robot::PB::ros2::builtin_interfaces::Time* unsafe_arena_release_map_load_time();

  private:
  const ::humanoid_robot::PB::ros2::builtin_interfaces::Time& _internal_map_load_time() const;
  ::humanoid_robot::PB::ros2::builtin_interfaces::Time* _internal_mutable_map_load_time();

  public:
  // .humanoid_robot.PB.ros2.geometry_msgs.Pose origin = 5;
  bool has_origin() const;
  void clear_origin() ;
  const ::humanoid_robot::PB::ros2::geometry_msgs::Pose& origin() const;
  PROTOBUF_NODISCARD ::humanoid_robot::PB::ros2::geometry_msgs::Pose* release_origin();
  ::humanoid_robot::PB::ros2::geometry_msgs::Pose* mutable_origin();
  void set_allocated_origin(::humanoid_robot::PB::ros2::geometry_msgs::Pose* value);
  void unsafe_arena_set_allocated_origin(::humanoid_robot::PB::ros2::geometry_msgs::Pose* value);
  ::humanoid_robot::PB::ros2::geometry_msgs::Pose* unsafe_arena_release_origin();

  private:
  const ::humanoid_robot::PB::ros2::geometry_msgs::Pose& _internal_origin() const;
  ::humanoid_robot::PB::ros2::geometry_msgs::Pose* _internal_mutable_origin();

  public:
  // float resolution = 2;
  void clear_resolution() ;
  float resolution() const;
  void set_resolution(float value);

  private:
  float _internal_resolution() const;
  void _internal_set_resolution(float value);

  public:
  // uint32 width = 3;
  void clear_width() ;
  ::uint32_t width() const;
  void set_width(::uint32_t value);

  private:
  ::uint32_t _internal_width() const;
  void _internal_set_width(::uint32_t value);

  public:
  // uint32 height = 4;
  void clear_height() ;
  ::uint32_t height() const;
  void set_height(::uint32_t value);

  private:
  ::uint32_t _internal_height() const;
  void _internal_set_height(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.ros2.nav_msgs.MapMetaData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MapMetaData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::humanoid_robot::PB::ros2::builtin_interfaces::Time* map_load_time_;
    ::humanoid_robot::PB::ros2::geometry_msgs::Pose* origin_;
    float resolution_;
    ::uint32_t width_;
    ::uint32_t height_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ros2_2fnav_5fmsgs_2fMapMetaData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MapMetaData

// .humanoid_robot.PB.ros2.builtin_interfaces.Time map_load_time = 1;
inline bool MapMetaData::has_map_load_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.map_load_time_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::builtin_interfaces::Time& MapMetaData::_internal_map_load_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::builtin_interfaces::Time* p = _impl_.map_load_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::builtin_interfaces::Time&>(::humanoid_robot::PB::ros2::builtin_interfaces::_Time_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::builtin_interfaces::Time& MapMetaData::map_load_time() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.map_load_time)
  return _internal_map_load_time();
}
inline void MapMetaData::unsafe_arena_set_allocated_map_load_time(::humanoid_robot::PB::ros2::builtin_interfaces::Time* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.map_load_time_);
  }
  _impl_.map_load_time_ = reinterpret_cast<::humanoid_robot::PB::ros2::builtin_interfaces::Time*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.map_load_time)
}
inline ::humanoid_robot::PB::ros2::builtin_interfaces::Time* MapMetaData::release_map_load_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::builtin_interfaces::Time* released = _impl_.map_load_time_;
  _impl_.map_load_time_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::builtin_interfaces::Time* MapMetaData::unsafe_arena_release_map_load_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.map_load_time)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::humanoid_robot::PB::ros2::builtin_interfaces::Time* temp = _impl_.map_load_time_;
  _impl_.map_load_time_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::builtin_interfaces::Time* MapMetaData::_internal_mutable_map_load_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.map_load_time_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::builtin_interfaces::Time>(GetArena());
    _impl_.map_load_time_ = reinterpret_cast<::humanoid_robot::PB::ros2::builtin_interfaces::Time*>(p);
  }
  return _impl_.map_load_time_;
}
inline ::humanoid_robot::PB::ros2::builtin_interfaces::Time* MapMetaData::mutable_map_load_time() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::humanoid_robot::PB::ros2::builtin_interfaces::Time* _msg = _internal_mutable_map_load_time();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.map_load_time)
  return _msg;
}
inline void MapMetaData::set_allocated_map_load_time(::humanoid_robot::PB::ros2::builtin_interfaces::Time* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.map_load_time_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.map_load_time_ = reinterpret_cast<::humanoid_robot::PB::ros2::builtin_interfaces::Time*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.map_load_time)
}

// float resolution = 2;
inline void MapMetaData::clear_resolution() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resolution_ = 0;
}
inline float MapMetaData::resolution() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.resolution)
  return _internal_resolution();
}
inline void MapMetaData::set_resolution(float value) {
  _internal_set_resolution(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.resolution)
}
inline float MapMetaData::_internal_resolution() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resolution_;
}
inline void MapMetaData::_internal_set_resolution(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resolution_ = value;
}

// uint32 width = 3;
inline void MapMetaData::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0u;
}
inline ::uint32_t MapMetaData::width() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.width)
  return _internal_width();
}
inline void MapMetaData::set_width(::uint32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.width)
}
inline ::uint32_t MapMetaData::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void MapMetaData::_internal_set_width(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// uint32 height = 4;
inline void MapMetaData::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0u;
}
inline ::uint32_t MapMetaData::height() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.height)
  return _internal_height();
}
inline void MapMetaData::set_height(::uint32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.height)
}
inline ::uint32_t MapMetaData::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void MapMetaData::_internal_set_height(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// .humanoid_robot.PB.ros2.geometry_msgs.Pose origin = 5;
inline bool MapMetaData::has_origin() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.origin_ != nullptr);
  return value;
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Pose& MapMetaData::_internal_origin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::humanoid_robot::PB::ros2::geometry_msgs::Pose* p = _impl_.origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::humanoid_robot::PB::ros2::geometry_msgs::Pose&>(::humanoid_robot::PB::ros2::geometry_msgs::_Pose_default_instance_);
}
inline const ::humanoid_robot::PB::ros2::geometry_msgs::Pose& MapMetaData::origin() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.origin)
  return _internal_origin();
}
inline void MapMetaData::unsafe_arena_set_allocated_origin(::humanoid_robot::PB::ros2::geometry_msgs::Pose* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.origin_);
  }
  _impl_.origin_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Pose*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.origin)
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Pose* MapMetaData::release_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Pose* released = _impl_.origin_;
  _impl_.origin_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Pose* MapMetaData::unsafe_arena_release_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.origin)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Pose* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
  return temp;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Pose* MapMetaData::_internal_mutable_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.origin_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::humanoid_robot::PB::ros2::geometry_msgs::Pose>(GetArena());
    _impl_.origin_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Pose*>(p);
  }
  return _impl_.origin_;
}
inline ::humanoid_robot::PB::ros2::geometry_msgs::Pose* MapMetaData::mutable_origin() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::humanoid_robot::PB::ros2::geometry_msgs::Pose* _msg = _internal_mutable_origin();
  // @@protoc_insertion_point(field_mutable:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.origin)
  return _msg;
}
inline void MapMetaData::set_allocated_origin(::humanoid_robot::PB::ros2::geometry_msgs::Pose* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.origin_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.origin_ = reinterpret_cast<::humanoid_robot::PB::ros2::geometry_msgs::Pose*>(value);
  // @@protoc_insertion_point(field_set_allocated:humanoid_robot.PB.ros2.nav_msgs.MapMetaData.origin)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nav_msgs
}  // namespace ros2
}  // namespace PB
}  // namespace humanoid_robot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ros2_2fnav_5fmsgs_2fMapMetaData_2eproto_2epb_2eh
