#include "pb_export.h"
// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api_service/konka/perception.proto
#ifndef GRPC_api_5fservice_2fkonka_2fperception_2eproto__INCLUDED
#define GRPC_api_5fservice_2fkonka_2fperception_2eproto__INCLUDED

#include "api_service/konka/perception.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace konka {
namespace perception {

class chric_protobuf_api_service_konka PerceptionService final {
 public:
  static constexpr char const* service_full_name() {
    return "humanoid_robot.PB.api_service.konka.perception.PerceptionService";
  }
  class chric_protobuf_api_service_konka StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> AsyncCall(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(AsyncCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> PrepareAsyncCall(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(PrepareAsyncCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> CallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(CallStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> AsyncCallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(AsyncCallStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> PrepareAsyncCallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(PrepareAsyncCallStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::grpc::ClientReadReactor< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* AsyncCallRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PrepareAsyncCallRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* CallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* AsyncCallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PrepareAsyncCallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class chric_protobuf_api_service_konka Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> AsyncCall(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(AsyncCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> PrepareAsyncCall(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(PrepareAsyncCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> CallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(CallStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> AsyncCallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(AsyncCallStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>> PrepareAsyncCallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>>(PrepareAsyncCallStreamRaw(context, request, cq));
    }
    class chric_protobuf_api_service_konka async final :
      public StubInterface::async_interface {
     public:
      void Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response, std::function<void(::grpc::Status)>) override;
      void Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::grpc::ClientReadReactor< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* reactor) override;
     private:
      friend class chric_protobuf_api_service_konka Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* AsyncCallRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PrepareAsyncCallRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* CallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request) override;
    ::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* AsyncCallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PrepareAsyncCallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Call_;
    const ::grpc::internal::RpcMethod rpcmethod_CallStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class chric_protobuf_api_service_konka Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Call(::grpc::ServerContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response);
    virtual ::grpc::Status CallStream(::grpc::ServerContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Call() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCall(::grpc::ServerContext* context, ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::grpc::ServerAsyncResponseWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CallStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CallStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CallStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallStream(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallStream(::grpc::ServerContext* context, ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::grpc::ServerAsyncWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Call<WithAsyncMethod_CallStream<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Call() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response) { return this->Call(context, request, response); }));}
    void SetMessageAllocatorFor_Call(
        ::grpc::MessageAllocator< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Call(
      ::grpc::CallbackServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CallStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CallStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request) { return this->CallStream(context, request); }));
    }
    ~WithCallbackMethod_CallStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallStream(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* CallStream(
      ::grpc::CallbackServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Call<WithCallbackMethod_CallStream<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Call() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CallStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CallStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CallStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallStream(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Call() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CallStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CallStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CallStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallStream(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Call() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Call(context, request, response); }));
    }
    ~WithRawCallbackMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Call(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CallStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CallStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->CallStream(context, request); }));
    }
    ~WithRawCallbackMethod_CallStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallStream(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* CallStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Call() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* streamer) {
                       return this->StreamedCall(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest,::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Call<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_CallStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_CallStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* streamer) {
                       return this->StreamedCallStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_CallStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CallStream(::grpc::ServerContext* /*context*/, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* /*request*/, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedCallStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest,::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_CallStream<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Call<WithSplitStreamingMethod_CallStream<Service > > StreamedService;
};

}  // namespace perception
}  // namespace konka
}  // namespace api_service
}  // namespace PB
}  // namespace humanoid_robot


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_api_5fservice_2fkonka_2fperception_2eproto__INCLUDED
