// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api_service/konka/perception.proto

#include "api_service/konka/perception.pb.h"
#include "api_service/konka/perception.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace konka {
namespace perception {

static const char* PerceptionService_method_names[] = {
  "/humanoid_robot.PB.api_service.konka.perception.PerceptionService/Call",
  "/humanoid_robot.PB.api_service.konka.perception.PerceptionService/CallStream",
};

std::unique_ptr< PerceptionService::Stub> PerceptionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PerceptionService::Stub> stub(new PerceptionService::Stub(channel, options));
  return stub;
}

PerceptionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Call_(PerceptionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CallStream_(PerceptionService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status PerceptionService::Stub::Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Call_, context, request, response);
}

void PerceptionService::Stub::async::Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Call_, context, request, response, std::move(f));
}

void PerceptionService::Stub::async::Call(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Call_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PerceptionService::Stub::PrepareAsyncCallRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse, ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Call_, context, request);
}

::grpc::ClientAsyncResponseReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PerceptionService::Stub::AsyncCallRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCallRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PerceptionService::Stub::CallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>::Create(channel_.get(), rpcmethod_CallStream_, context, request);
}

void PerceptionService::Stub::async::CallStream(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::grpc::ClientReadReactor< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_CallStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PerceptionService::Stub::AsyncCallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>::Create(channel_.get(), cq, rpcmethod_CallStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* PerceptionService::Stub::PrepareAsyncCallStreamRaw(::grpc::ClientContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>::Create(channel_.get(), cq, rpcmethod_CallStream_, context, request, false, nullptr);
}

PerceptionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PerceptionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PerceptionService::Service, ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PerceptionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* req,
             ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* resp) {
               return service->Call(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PerceptionService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< PerceptionService::Service, ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>(
          [](PerceptionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* req,
             ::grpc::ServerWriter<::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* writer) {
               return service->CallStream(ctx, req, writer);
             }, this)));
}

PerceptionService::Service::~Service() {
}

::grpc::Status PerceptionService::Service::Call(::grpc::ServerContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PerceptionService::Service::CallStream(::grpc::ServerContext* context, const ::humanoid_robot::PB::api_service::konka::perception::UnifiedRequest* request, ::grpc::ServerWriter< ::humanoid_robot::PB::api_service::konka::perception::UnifiedResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace humanoid_robot
}  // namespace PB
}  // namespace api_service
}  // namespace konka
}  // namespace perception

