// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api_service/tangpa/system.proto
// Protobuf C++ Version: 5.29.0

#include "api_service/tangpa/system.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace tangpa {
namespace system {

inline constexpr RobotStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_codes_{},
        state_desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        state_id_{::int64_t{0}},
        battery_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RobotStatus::RobotStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RobotStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotStatusDefaultTypeInternal() {}
  union {
    RobotStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotStatusDefaultTypeInternal _RobotStatus_default_instance_;

inline constexpr BatteryPercentage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : info_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BatteryPercentage::BatteryPercentage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BatteryPercentageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatteryPercentageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatteryPercentageDefaultTypeInternal() {}
  union {
    BatteryPercentage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatteryPercentageDefaultTypeInternal _BatteryPercentage_default_instance_;

inline constexpr DiagnosticMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        messages_{nullptr},
        result_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DiagnosticMessage::DiagnosticMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DiagnosticMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DiagnosticMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DiagnosticMessageDefaultTypeInternal() {}
  union {
    DiagnosticMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DiagnosticMessageDefaultTypeInternal _DiagnosticMessage_default_instance_;
}  // namespace system
}  // namespace tangpa
}  // namespace api_service
}  // namespace PB
}  // namespace humanoid_robot
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_api_5fservice_2ftangpa_2fsystem_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_api_5fservice_2ftangpa_2fsystem_2eproto = nullptr;
const ::uint32_t
    TableStruct_api_5fservice_2ftangpa_2fsystem_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::BatteryPercentage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::BatteryPercentage, _impl_.info_),
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::DiagnosticMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::DiagnosticMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::DiagnosticMessage, _impl_.messages_),
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::DiagnosticMessage, _impl_.result_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::RobotStatus, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::RobotStatus, _impl_.state_id_),
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::RobotStatus, _impl_.state_desc_),
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::RobotStatus, _impl_.battery_),
        PROTOBUF_FIELD_OFFSET(::humanoid_robot::PB::api_service::tangpa::system::RobotStatus, _impl_.error_codes_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::humanoid_robot::PB::api_service::tangpa::system::BatteryPercentage)},
        {9, 19, -1, sizeof(::humanoid_robot::PB::api_service::tangpa::system::DiagnosticMessage)},
        {21, -1, -1, sizeof(::humanoid_robot::PB::api_service::tangpa::system::RobotStatus)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::humanoid_robot::PB::api_service::tangpa::system::_BatteryPercentage_default_instance_._instance,
    &::humanoid_robot::PB::api_service::tangpa::system::_DiagnosticMessage_default_instance_._instance,
    &::humanoid_robot::PB::api_service::tangpa::system::_RobotStatus_default_instance_._instance,
};
const char descriptor_table_protodef_api_5fservice_2ftangpa_2fsystem_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037api_service/tangpa/system.proto\022+human"
    "oid_robot.PB.api_service.tangpa.system\032*"
    "ros2/diagnostic_msgs/DiagnosticArray.pro"
    "to\"!\n\021BatteryPercentage\022\014\n\004info\030\001 \001(\t\"n\n"
    "\021DiagnosticMessage\022I\n\010messages\030\001 \001(\01327.h"
    "umanoid_robot.PB.ros2.diagnostic_msgs.Di"
    "agnosticArray\022\016\n\006result\030\002 \001(\005\"Y\n\013RobotSt"
    "atus\022\020\n\010state_id\030\001 \001(\003\022\022\n\nstate_desc\030\002 \001"
    "(\t\022\017\n\007battery\030\003 \001(\002\022\023\n\013error_codes\030\004 \003(\t"
    "*0\n\014TangPaStatus\022\013\n\007SUCCESS\020\000\022\023\n\006FAILED\020"
    "\377\377\377\377\377\377\377\377\377\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto_deps[1] =
    {
        &::descriptor_table_ros2_2fdiagnostic_5fmsgs_2fDiagnosticArray_2eproto,
};
static ::absl::once_flag descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto = {
    false,
    false,
    418,
    descriptor_table_protodef_api_5fservice_2ftangpa_2fsystem_2eproto,
    "api_service/tangpa/system.proto",
    &descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto_once,
    descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_api_5fservice_2ftangpa_2fsystem_2eproto::offsets,
    file_level_enum_descriptors_api_5fservice_2ftangpa_2fsystem_2eproto,
    file_level_service_descriptors_api_5fservice_2ftangpa_2fsystem_2eproto,
};
namespace humanoid_robot {
namespace PB {
namespace api_service {
namespace tangpa {
namespace system {
const ::google::protobuf::EnumDescriptor* TangPaStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto);
  return file_level_enum_descriptors_api_5fservice_2ftangpa_2fsystem_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TangPaStatus_internal_data_[] = {
    196607u, 0u, };
bool TangPaStatus_IsValid(int value) {
  return -1 <= value && value <= 0;
}
// ===================================================================

class BatteryPercentage::_Internal {
 public:
};

BatteryPercentage::BatteryPercentage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
}
inline PROTOBUF_NDEBUG_INLINE BatteryPercentage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::humanoid_robot::PB::api_service::tangpa::system::BatteryPercentage& from_msg)
      : info_(arena, from.info_),
        _cached_size_{0} {}

BatteryPercentage::BatteryPercentage(
    ::google::protobuf::Arena* arena,
    const BatteryPercentage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BatteryPercentage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
}
inline PROTOBUF_NDEBUG_INLINE BatteryPercentage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : info_(arena),
        _cached_size_{0} {}

inline void BatteryPercentage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BatteryPercentage::~BatteryPercentage() {
  // @@protoc_insertion_point(destructor:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
  SharedDtor(*this);
}
inline void BatteryPercentage::SharedDtor(MessageLite& self) {
  BatteryPercentage& this_ = static_cast<BatteryPercentage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.info_.Destroy();
  this_._impl_.~Impl_();
}

inline void* BatteryPercentage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BatteryPercentage(arena);
}
constexpr auto BatteryPercentage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BatteryPercentage),
                                            alignof(BatteryPercentage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BatteryPercentage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BatteryPercentage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BatteryPercentage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BatteryPercentage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BatteryPercentage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BatteryPercentage>(), &BatteryPercentage::ByteSizeLong,
            &BatteryPercentage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BatteryPercentage, _impl_._cached_size_),
        false,
    },
    &BatteryPercentage::kDescriptorMethods,
    &descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BatteryPercentage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 74, 2> BatteryPercentage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_robot::PB::api_service::tangpa::system::BatteryPercentage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string info = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BatteryPercentage, _impl_.info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string info = 1;
    {PROTOBUF_FIELD_OFFSET(BatteryPercentage, _impl_.info_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\75\4\0\0\0\0\0\0"
    "humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage"
    "info"
  }},
};

PROTOBUF_NOINLINE void BatteryPercentage::Clear() {
// @@protoc_insertion_point(message_clear_start:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.info_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BatteryPercentage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BatteryPercentage& this_ = static_cast<const BatteryPercentage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BatteryPercentage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BatteryPercentage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string info = 1;
          if (!this_._internal_info().empty()) {
            const std::string& _s = this_._internal_info();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage.info");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BatteryPercentage::ByteSizeLong(const MessageLite& base) {
          const BatteryPercentage& this_ = static_cast<const BatteryPercentage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BatteryPercentage::ByteSizeLong() const {
          const BatteryPercentage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string info = 1;
            if (!this_._internal_info().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_info());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BatteryPercentage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BatteryPercentage*>(&to_msg);
  auto& from = static_cast<const BatteryPercentage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_info().empty()) {
    _this->_internal_set_info(from._internal_info());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BatteryPercentage::CopyFrom(const BatteryPercentage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:humanoid_robot.PB.api_service.tangpa.system.BatteryPercentage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BatteryPercentage::InternalSwap(BatteryPercentage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.info_, &other->_impl_.info_, arena);
}

::google::protobuf::Metadata BatteryPercentage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DiagnosticMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DiagnosticMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_._has_bits_);
};

void DiagnosticMessage::clear_messages() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.messages_ != nullptr) _impl_.messages_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
DiagnosticMessage::DiagnosticMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
}
inline PROTOBUF_NDEBUG_INLINE DiagnosticMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::humanoid_robot::PB::api_service::tangpa::system::DiagnosticMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

DiagnosticMessage::DiagnosticMessage(
    ::google::protobuf::Arena* arena,
    const DiagnosticMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DiagnosticMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.messages_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray>(
                              arena, *from._impl_.messages_)
                        : nullptr;
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
}
inline PROTOBUF_NDEBUG_INLINE DiagnosticMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DiagnosticMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, messages_),
           0,
           offsetof(Impl_, result_) -
               offsetof(Impl_, messages_) +
               sizeof(Impl_::result_));
}
DiagnosticMessage::~DiagnosticMessage() {
  // @@protoc_insertion_point(destructor:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
  SharedDtor(*this);
}
inline void DiagnosticMessage::SharedDtor(MessageLite& self) {
  DiagnosticMessage& this_ = static_cast<DiagnosticMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.messages_;
  this_._impl_.~Impl_();
}

inline void* DiagnosticMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DiagnosticMessage(arena);
}
constexpr auto DiagnosticMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DiagnosticMessage),
                                            alignof(DiagnosticMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DiagnosticMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DiagnosticMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DiagnosticMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DiagnosticMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DiagnosticMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DiagnosticMessage>(), &DiagnosticMessage::ByteSizeLong,
            &DiagnosticMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_._cached_size_),
        false,
    },
    &DiagnosticMessage::kDescriptorMethods,
    &descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DiagnosticMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> DiagnosticMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_robot::PB::api_service::tangpa::system::DiagnosticMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 result = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DiagnosticMessage, _impl_.result_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_.result_)}},
    // .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticArray messages = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_.messages_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticArray messages = 1;
    {PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_.messages_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 result = 2;
    {PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_.result_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void DiagnosticMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.messages_ != nullptr);
    _impl_.messages_->Clear();
  }
  _impl_.result_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DiagnosticMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DiagnosticMessage& this_ = static_cast<const DiagnosticMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DiagnosticMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DiagnosticMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticArray messages = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.messages_, this_._impl_.messages_->GetCachedSize(), target,
                stream);
          }

          // int32 result = 2;
          if (this_._internal_result() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DiagnosticMessage::ByteSizeLong(const MessageLite& base) {
          const DiagnosticMessage& this_ = static_cast<const DiagnosticMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DiagnosticMessage::ByteSizeLong() const {
          const DiagnosticMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .humanoid_robot.PB.ros2.diagnostic_msgs.DiagnosticArray messages = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.messages_);
            }
          }
           {
            // int32 result = 2;
            if (this_._internal_result() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DiagnosticMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DiagnosticMessage*>(&to_msg);
  auto& from = static_cast<const DiagnosticMessage&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.messages_ != nullptr);
    if (_this->_impl_.messages_ == nullptr) {
      _this->_impl_.messages_ =
          ::google::protobuf::Message::CopyConstruct<::humanoid_robot::PB::ros2::diagnostic_msgs::DiagnosticArray>(arena, *from._impl_.messages_);
    } else {
      _this->_impl_.messages_->MergeFrom(*from._impl_.messages_);
    }
  }
  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DiagnosticMessage::CopyFrom(const DiagnosticMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:humanoid_robot.PB.api_service.tangpa.system.DiagnosticMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DiagnosticMessage::InternalSwap(DiagnosticMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_.result_)
      + sizeof(DiagnosticMessage::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(DiagnosticMessage, _impl_.messages_)>(
          reinterpret_cast<char*>(&_impl_.messages_),
          reinterpret_cast<char*>(&other->_impl_.messages_));
}

::google::protobuf::Metadata DiagnosticMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RobotStatus::_Internal {
 public:
};

RobotStatus::RobotStatus(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
}
inline PROTOBUF_NDEBUG_INLINE RobotStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::humanoid_robot::PB::api_service::tangpa::system::RobotStatus& from_msg)
      : error_codes_{visibility, arena, from.error_codes_},
        state_desc_(arena, from.state_desc_),
        _cached_size_{0} {}

RobotStatus::RobotStatus(
    ::google::protobuf::Arena* arena,
    const RobotStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RobotStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, state_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, state_id_),
           offsetof(Impl_, battery_) -
               offsetof(Impl_, state_id_) +
               sizeof(Impl_::battery_));

  // @@protoc_insertion_point(copy_constructor:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
}
inline PROTOBUF_NDEBUG_INLINE RobotStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : error_codes_{visibility, arena},
        state_desc_(arena),
        _cached_size_{0} {}

inline void RobotStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, state_id_),
           0,
           offsetof(Impl_, battery_) -
               offsetof(Impl_, state_id_) +
               sizeof(Impl_::battery_));
}
RobotStatus::~RobotStatus() {
  // @@protoc_insertion_point(destructor:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
  SharedDtor(*this);
}
inline void RobotStatus::SharedDtor(MessageLite& self) {
  RobotStatus& this_ = static_cast<RobotStatus&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.state_desc_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RobotStatus::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RobotStatus(arena);
}
constexpr auto RobotStatus::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.error_codes_) +
          decltype(RobotStatus::_impl_.error_codes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(RobotStatus), alignof(RobotStatus), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RobotStatus::PlacementNew_,
                                 sizeof(RobotStatus),
                                 alignof(RobotStatus));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RobotStatus::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RobotStatus_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RobotStatus::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RobotStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RobotStatus::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RobotStatus>(), &RobotStatus::ByteSizeLong,
            &RobotStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_._cached_size_),
        false,
    },
    &RobotStatus::kDescriptorMethods,
    &descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RobotStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 85, 2> RobotStatus::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_robot::PB::api_service::tangpa::system::RobotStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string error_codes = 4;
    {::_pbi::TcParser::FastUR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.error_codes_)}},
    // int64 state_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RobotStatus, _impl_.state_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.state_id_)}},
    // string state_desc = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.state_desc_)}},
    // float battery = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.battery_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 state_id = 1;
    {PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.state_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string state_desc = 2;
    {PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.state_desc_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float battery = 3;
    {PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.battery_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // repeated string error_codes = 4;
    {PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.error_codes_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\67\0\12\0\13\0\0\0"
    "humanoid_robot.PB.api_service.tangpa.system.RobotStatus"
    "state_desc"
    "error_codes"
  }},
};

PROTOBUF_NOINLINE void RobotStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_codes_.Clear();
  _impl_.state_desc_.ClearToEmpty();
  ::memset(&_impl_.state_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.battery_) -
      reinterpret_cast<char*>(&_impl_.state_id_)) + sizeof(_impl_.battery_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RobotStatus::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RobotStatus& this_ = static_cast<const RobotStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RobotStatus::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RobotStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 state_id = 1;
          if (this_._internal_state_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_state_id(), target);
          }

          // string state_desc = 2;
          if (!this_._internal_state_desc().empty()) {
            const std::string& _s = this_._internal_state_desc();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "humanoid_robot.PB.api_service.tangpa.system.RobotStatus.state_desc");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // float battery = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_battery()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_battery(), target);
          }

          // repeated string error_codes = 4;
          for (int i = 0, n = this_._internal_error_codes_size(); i < n; ++i) {
            const auto& s = this_._internal_error_codes().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "humanoid_robot.PB.api_service.tangpa.system.RobotStatus.error_codes");
            target = stream->WriteString(4, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RobotStatus::ByteSizeLong(const MessageLite& base) {
          const RobotStatus& this_ = static_cast<const RobotStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RobotStatus::ByteSizeLong() const {
          const RobotStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string error_codes = 4;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_error_codes().size());
              for (int i = 0, n = this_._internal_error_codes().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_error_codes().Get(i));
              }
            }
          }
           {
            // string state_desc = 2;
            if (!this_._internal_state_desc().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_state_desc());
            }
            // int64 state_id = 1;
            if (this_._internal_state_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_state_id());
            }
            // float battery = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_battery()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RobotStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RobotStatus*>(&to_msg);
  auto& from = static_cast<const RobotStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_error_codes()->MergeFrom(from._internal_error_codes());
  if (!from._internal_state_desc().empty()) {
    _this->_internal_set_state_desc(from._internal_state_desc());
  }
  if (from._internal_state_id() != 0) {
    _this->_impl_.state_id_ = from._impl_.state_id_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_battery()) != 0) {
    _this->_impl_.battery_ = from._impl_.battery_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotStatus::CopyFrom(const RobotStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:humanoid_robot.PB.api_service.tangpa.system.RobotStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RobotStatus::InternalSwap(RobotStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.error_codes_.InternalSwap(&other->_impl_.error_codes_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.state_desc_, &other->_impl_.state_desc_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.battery_)
      + sizeof(RobotStatus::_impl_.battery_)
      - PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.state_id_)>(
          reinterpret_cast<char*>(&_impl_.state_id_),
          reinterpret_cast<char*>(&other->_impl_.state_id_));
}

::google::protobuf::Metadata RobotStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace system
}  // namespace tangpa
}  // namespace api_service
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_api_5fservice_2ftangpa_2fsystem_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
