#include "pb_export.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: konka_ros2_interfaces/navigation/loc_msg/ResStatus.proto
// Protobuf C++ Version: 5.29.0

#ifndef konka_5fros2_5finterfaces_2fnavigation_2floc_5fmsg_2fResStatus_2eproto_2epb_2eh
#define konka_5fros2_5finterfaces_2fnavigation_2floc_5fmsg_2fResStatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_konka_5fros2_5finterfaces_2fnavigation_2floc_5fmsg_2fResStatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_konka_5fros2_5finterfaces_2fnavigation_2floc_5fmsg_2fResStatus_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_konka_5fros2_5finterfaces_2fnavigation_2floc_5fmsg_2fResStatus_2eproto;
namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace navigation {
namespace loc_msg {
class ResStatus;
struct ResStatusDefaultTypeInternal;
extern ResStatusDefaultTypeInternal _ResStatus_default_instance_;
}  // namespace loc_msg
}  // namespace navigation
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace humanoid_robot {
namespace PB {
namespace konka_ros2_interfaces {
namespace navigation {
namespace loc_msg {
enum ResStatus_ResStatusEnum : int {
  ResStatus_ResStatusEnum_RESPONSE_SUCCESS = 0,
  ResStatus_ResStatusEnum_ERROR_UNKNOWN_SERVICE = 17825792,
  ResStatus_ResStatusEnum_ERROR_PARSE_FAILED = 17829888,
  ResStatus_ResStatusEnum_ERROR_DATA_GET_FAILED = 17829889,
  ResStatus_ResStatusEnum_ResStatus_ResStatusEnum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ResStatus_ResStatusEnum_ResStatus_ResStatusEnum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ResStatus_ResStatusEnum_IsValid(int value);
extern const uint32_t ResStatus_ResStatusEnum_internal_data_[];
constexpr ResStatus_ResStatusEnum ResStatus_ResStatusEnum_ResStatusEnum_MIN = static_cast<ResStatus_ResStatusEnum>(0);
constexpr ResStatus_ResStatusEnum ResStatus_ResStatusEnum_ResStatusEnum_MAX = static_cast<ResStatus_ResStatusEnum>(17829889);
constexpr int ResStatus_ResStatusEnum_ResStatusEnum_ARRAYSIZE = 17829889 + 1;
const ::google::protobuf::EnumDescriptor*
ResStatus_ResStatusEnum_descriptor();
template <typename T>
const std::string& ResStatus_ResStatusEnum_Name(T value) {
  static_assert(std::is_same<T, ResStatus_ResStatusEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ResStatusEnum_Name().");
  return ::google::protobuf::internal::NameOfEnum(ResStatus_ResStatusEnum_descriptor(), value);
}
inline bool ResStatus_ResStatusEnum_Parse(absl::string_view name, ResStatus_ResStatusEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResStatus_ResStatusEnum>(
      ResStatus_ResStatusEnum_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class chric_protobuf_konka_ros2_interfaces ResStatus final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:humanoid_robot.PB.konka_ros2_interfaces.navigation.loc_msg.ResStatus) */ {
 public:
  inline ResStatus() : ResStatus(nullptr) {}
  ~ResStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResStatus* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline ResStatus(const ResStatus& from) : ResStatus(nullptr, from) {}
  inline ResStatus(ResStatus&& from) noexcept
      : ResStatus(nullptr, std::move(from)) {}
  inline ResStatus& operator=(const ResStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResStatus& operator=(ResStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResStatus* internal_default_instance() {
    return reinterpret_cast<const ResStatus*>(
        &_ResStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ResStatus& a, ResStatus& b) { a.Swap(&b); }
  inline void Swap(ResStatus* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResStatus* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResStatus& from) { ResStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResStatus* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "humanoid_robot.PB.konka_ros2_interfaces.navigation.loc_msg.ResStatus"; }

 protected:
  explicit ResStatus(::google::protobuf::Arena* arena);
  ResStatus(::google::protobuf::Arena* arena, const ResStatus& from);
  ResStatus(::google::protobuf::Arena* arena, ResStatus&& from) noexcept
      : ResStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ResStatusEnum = ResStatus_ResStatusEnum;
  static constexpr ResStatusEnum RESPONSE_SUCCESS = ResStatus_ResStatusEnum_RESPONSE_SUCCESS;
  static constexpr ResStatusEnum ERROR_UNKNOWN_SERVICE = ResStatus_ResStatusEnum_ERROR_UNKNOWN_SERVICE;
  static constexpr ResStatusEnum ERROR_PARSE_FAILED = ResStatus_ResStatusEnum_ERROR_PARSE_FAILED;
  static constexpr ResStatusEnum ERROR_DATA_GET_FAILED = ResStatus_ResStatusEnum_ERROR_DATA_GET_FAILED;
  static inline bool ResStatusEnum_IsValid(int value) {
    return ResStatus_ResStatusEnum_IsValid(value);
  }
  static constexpr ResStatusEnum ResStatusEnum_MIN = ResStatus_ResStatusEnum_ResStatusEnum_MIN;
  static constexpr ResStatusEnum ResStatusEnum_MAX = ResStatus_ResStatusEnum_ResStatusEnum_MAX;
  static constexpr int ResStatusEnum_ARRAYSIZE = ResStatus_ResStatusEnum_ResStatusEnum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* ResStatusEnum_descriptor() {
    return ResStatus_ResStatusEnum_descriptor();
  }
  template <typename T>
  static inline const std::string& ResStatusEnum_Name(T value) {
    return ResStatus_ResStatusEnum_Name(value);
  }
  static inline bool ResStatusEnum_Parse(absl::string_view name, ResStatusEnum* value) {
    return ResStatus_ResStatusEnum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // uint32 status = 1;
  void clear_status() ;
  ::uint32_t status() const;
  void set_status(::uint32_t value);

  private:
  ::uint32_t _internal_status() const;
  void _internal_set_status(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:humanoid_robot.PB.konka_ros2_interfaces.navigation.loc_msg.ResStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ResStatus& from_msg);
    ::uint32_t status_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_konka_5fros2_5finterfaces_2fnavigation_2floc_5fmsg_2fResStatus_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ResStatus

// uint32 status = 1;
inline void ResStatus::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0u;
}
inline ::uint32_t ResStatus::status() const {
  // @@protoc_insertion_point(field_get:humanoid_robot.PB.konka_ros2_interfaces.navigation.loc_msg.ResStatus.status)
  return _internal_status();
}
inline void ResStatus::set_status(::uint32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:humanoid_robot.PB.konka_ros2_interfaces.navigation.loc_msg.ResStatus.status)
}
inline ::uint32_t ResStatus::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void ResStatus::_internal_set_status(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace loc_msg
}  // namespace navigation
}  // namespace konka_ros2_interfaces
}  // namespace PB
}  // namespace humanoid_robot


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::humanoid_robot::PB::konka_ros2_interfaces::navigation::loc_msg::ResStatus_ResStatusEnum> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::humanoid_robot::PB::konka_ros2_interfaces::navigation::loc_msg::ResStatus_ResStatusEnum>() {
  return ::humanoid_robot::PB::konka_ros2_interfaces::navigation::loc_msg::ResStatus_ResStatusEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // konka_5fros2_5finterfaces_2fnavigation_2floc_5fmsg_2fResStatus_2eproto_2epb_2eh
